// AP World History: Modern practice kit — question bank.
//
// HONESTY NOTE (please keep it): every stimulus here is an original paraphrase,
// summary or adapted data table written for this project. Nothing is a verbatim
// excerpt of a historical document, and no number here should be cited as data.
// Real people and documents are named only where the substance is well
// established; the wording is ours. Questions follow the published College Board
// course framework (Units 1-9, c. 1200 to the present). This kit is unofficial
// and not affiliated with or endorsed by the College Board.
//
// To add a question set:  set(id, unit, st(source, body), q(...), q(...), q(...))
// Each q: q(skill, question, [4 choices], answerIndex, [4 rationales], [atlas event ids])
// Then run:  node apcheck.mjs

(function () {
  const MCQ = [], SAQ = [], LEQ = [];
  // st(sourceLine, body, extras) — extras: {kind:"table", head:[...], rows:[[...]]}
  const st = (source, body, o = {}) => ({ source, body, ...o });

  // Choice order is shuffled deterministically from each question's id, so the
  // answer key stays evenly spread across A/B/C/D without anyone having to plan
  // it. Write choices in whatever order reads best and put the correct one
  // wherever you like; the shuffle is stable, so scoring and review always agree.
  const PERMS = [];
  (function perm(head, rest) {
    if (!rest.length) return PERMS.push(head);
    rest.forEach((x, i) => perm(head.concat(x), rest.filter((_, j) => j !== i)));
  })([], [0, 1, 2, 3]);
  const hash = s => { let h = 2166136261; for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return h >>> 0; };
  const shuffle = q => {
    const p = PERMS[hash(q.id) % PERMS.length];
    return { ...q, choices: p.map(i => q.choices[i]), why: p.map(i => q.why[i]), answer: p.indexOf(q.answer) };
  };
  const set = (id, unit, stim, ...qs) => MCQ.push({
    id, unit, stim,
    qs: qs.map((q, i) => shuffle({ ...q, id: id + "." + "abcd"[i] })),
  });
  const q = (skill, text, choices, answer, why, atlas = []) => ({ skill, text, choices, answer, why, atlas });

  // ---------------- Unit 1 — The Global Tapestry (c. 1200 – c. 1450) ----------------

  set("u1s1", 1, st(
    "Paraphrase of advice written by a Song dynasty official on the imperial examinations, c. 1200.",
    "The state is served best when offices go to men who have mastered the classics, not to men who have only inherited land. Let the candidate sit in the examination hall and write on the Analects; let the examiners read his work without knowing his family. In this way the empire is governed by learning, and learning is open to any household that can spare a son for study."),
    q("causation",
      "The practices described in the passage most directly contributed to which development in Song China?",
      ["The growth of a scholar-gentry class that staffed an expanding imperial bureaucracy",
       "The rise of a hereditary warrior aristocracy that controlled provincial government",
       "The replacement of Confucian administration with Buddhist monastic rule",
       "The transfer of tax collection to foreign merchant companies"],
      0,
      ["Correct. Examinations produced a large class of classically educated officials — the scholar-gentry — who ran Song government.",
       "Hereditary warrior elites describe Japan and medieval Europe, not the Song civil service.",
       "Buddhism was widespread in Song China, but monks did not replace the imperial bureaucracy.",
       "Song tax collection remained a function of the state bureaucracy, not of foreign firms."],
      ["qin", "confucius"]),
    q("process",
      "The values expressed in the passage are best understood as evidence of which broader intellectual development?",
      ["The spread of Legalist thought rejecting moral education",
       "The revival and reworking of Confucian thought known as Neo-Confucianism",
       "The adoption of Daoist withdrawal from public service",
       "The arrival of Islamic scholarship through the Indian Ocean trade"],
      1,
      ["Legalism emphasized harsh law over classical learning and moral cultivation.",
       "Correct. Song thinkers reworked Confucian ethics into Neo-Confucianism, which anchored the examination curriculum.",
       "Daoism urged withdrawal from official life; the passage urges the opposite.",
       "Islamic learning did reach China, but the passage is rooted in the Confucian classics."],
      ["confucius"]),
    q("comparison",
      "Compared with the system described in the passage, political authority in western Europe in the same period rested more heavily on",
      ["competitive written examinations administered by the church",
       "election of rulers by assemblies of urban merchants",
       "hereditary landholding and oaths of personal loyalty",
       "appointment of officials by Muslim legal scholars"],
      2,
      ["Europe had no imperial examination system; clerical schooling was not a route into state office in this way.",
       "Some towns governed themselves, but kingdoms were not ruled by merchant election.",
       "Correct. European lords and kings built authority on inherited land and sworn personal obligation.",
       "Rule through ulama and Islamic law describes parts of Dar al-Islam, not Latin Christendom."],
      ["magnacarta"]));

  set("u1s2", 1, st(
    "Paraphrase of a North African scholar's description of the empire of Mali, written after travelling there, c. 1352.",
    "The sultan is generous and his subjects are safe on the roads; a traveller may go alone without fear of robbers. Gold comes to his court from the south, and in the city of Timbuktu I found students of law and copies of books brought from Cairo. Yet the women of the court appear before men unveiled and speak freely, and at festivals the people keep customs that no scholar of our cities would approve."),
    q("sourcing",
      "A historian evaluating this account as evidence about Mali would most need to take into account that the author",
      ["was an outsider measuring Mali against the norms of his own Muslim society",
       "had no access to rulers or officials anywhere in West Africa",
       "wrote several centuries after the events he claims to describe",
       "was employed by the Malian court to record its official history"],
      0,
      ["Correct. The praise and the disapproval both reflect the author's own standards, which shapes what he notices and judges.",
       "The passage describes the sultan's court directly, so lack of access is not the issue.",
       "The account is presented as contemporary travel description, not a late compilation.",
       "Nothing indicates court employment, and his criticism suggests he was not an official chronicler."],
      ["mansamusa"]),
    q("causation",
      "The wealth and scholarly activity described were most directly the result of Mali's position",
      ["at the western end of the Silk Roads linking China to the Mediterranean",
       "astride trans-Saharan caravan routes exchanging gold for salt and goods from the north",
       "as the main supplier of spices to Indian Ocean merchants",
       "as the center of silver mining for the Atlantic economy"],
      1,
      ["The Silk Roads ran across Eurasia; Mali's trade crossed the Sahara.",
       "Correct. Camel caravans carried Malian gold north and brought salt, textiles, books and Islamic learning south.",
       "Spices came primarily from South and Southeast Asia.",
       "Large-scale silver mining for an Atlantic economy belongs to the period after 1500."],
      ["camel", "mansamusa", "catalan"]),
    q("cct",
      "The final sentence of the passage best illustrates which pattern in the spread of religions in this period?",
      ["Rulers who adopted a new faith generally forced the rapid abandonment of older practices",
       "New faiths spread mainly through conquest rather than trade",
       "Converted societies commonly blended the new faith with existing local customs",
       "Islam spread in West Africa only among enslaved populations"],
      2,
      ["The passage shows older customs continuing, not being abandoned.",
       "Islam reached West Africa largely along trade routes, not by conquest.",
       "Correct. The coexistence of Islamic learning with local custom is a classic example of syncretism.",
       "Islam in Mali was adopted by rulers, merchants and scholars, including elites."],
      ["mansamusa", "islam"]));

  // ---------------- Unit 2 — Networks of Exchange (c. 1200 – c. 1450) ----------------

  set("u2s1", 2, st(
    "Selected transfers along Afro-Eurasian exchange networks, c. 1200–1450. Table compiled for this practice set from widely accepted accounts; directions are simplified.",
    null,
    { kind: "table",
      head: ["Item", "Moved roughly from", "Toward"],
      rows: [["Papermaking", "China", "Central Asia, Baghdad, then Europe"],
             ["Gunpowder and firearms", "China", "Mongol Eurasia, the Middle East, Europe"],
             ["Cotton textiles", "South Asia", "East Africa and Southeast Asia"],
             ["Champa rice", "Vietnam", "Southern China"],
             ["Bubonic plague", "Inner Asia", "Black Sea ports, the Middle East, Europe"]] }),
    q("causation",
      "The transfers shown in the table were most directly facilitated by",
      ["the imposition of a single religion across Eurasia",
       "Mongol control of overland routes together with monsoon-driven maritime trade",
       "the construction of canals linking the Mediterranean to the Indian Ocean",
       "the replacement of merchant trade by state-run monopolies everywhere"],
      1,
      ["Eurasia remained religiously diverse; no single faith unified these networks.",
       "Correct. Mongol-era security on land routes and predictable monsoon sailing together moved goods, technologies and microbes.",
       "No such canal existed before the Suez Canal in 1869.",
       "States taxed and sometimes sponsored trade, but merchants and diasporas did the moving."],
      ["genghis", "silkroad", "monsoon", "papersamarkand"]),
    q("evidence",
      "The spread of champa rice shown in the table most directly supported which development?",
      ["Population growth in China as double cropping raised food supply",
       "The collapse of Chinese agriculture and a turn to herding",
       "The end of Chinese reliance on the Grand Canal",
       "The shift of Chinese farming from grain to cotton"],
      0,
      ["Correct. Fast-ripening rice allowed more harvests per year, supporting one of the period's great population increases.",
       "The transfer expanded farming rather than ending it.",
       "The Grand Canal remained central to moving grain within China.",
       "Cotton mattered in China, but champa rice is a food grain story."],
      ["rice", "paper"]),
    q("causation",
      "Which best explains why the last item in the table spread as widely as it did?",
      ["Deliberate use of disease as a weapon by most states of the period",
       "A sudden change in climate that created the disease",
       "The same dense trade routes and port cities that carried goods also carried rats, fleas and people",
       "The absence of cities large enough to sustain an epidemic"],
      2,
      ["Isolated instances are alleged, but the pandemic's reach is explained by ordinary trade.",
       "Climate may have affected rodent populations, but trade networks explain the spread.",
       "Correct. Integration was the mechanism: caravans and ships linked populations that had been epidemiologically separate.",
       "Large, crowded cities are exactly what made the pandemic devastating."],
      ["blackdeath", "silkroad", "monsoon"]));

  set("u2s2", 2, st(
    "Paraphrase of a fourteenth-century traveller's description of an Indian Ocean port.",
    "In this harbor I counted ships from China, from Arabia and from the coast of Africa. Merchants from each land live in their own quarter of the city with their own judge, and they marry locally and learn the speech of the place. The ruler takes a share of every cargo and in return keeps the harbor safe and the warehouses guarded. The captains wait for the season, for they know the wind will turn and carry them home."),
    q("process",
      "The arrangement of merchant quarters described in the passage is the best example of which common feature of Indian Ocean trade?",
      ["Diasporic merchant communities settling in foreign port cities",
       "Armed trading companies ruling ports as colonies",
       "Religious uniformity enforced by port authorities",
       "State monopolies that barred foreign merchants"],
      0,
      ["Correct. Resident communities of foreign merchants — diasporic communities — were characteristic of these ports.",
       "Company rule over Indian Ocean ports belongs mainly to the period after 1500.",
       "These ports were notably plural in religion and law.",
       "Rulers taxed and protected foreign merchants rather than excluding them."],
      ["monsoon", "malacca"]),
    q("evidence",
      "The final sentence most directly reflects the importance of",
      ["the magnetic compass in allowing ships to sail against the wind",
       "knowledge of monsoon wind patterns in timing long-distance voyages",
       "canal construction in shortening sea routes",
       "state navies in suppressing piracy in the Red Sea"],
      1,
      ["The compass mattered, but the sentence is about waiting for a season.",
       "Correct. Seasonal reversal of monsoon winds set the rhythm of Indian Ocean sailing.",
       "No canals linked these waters in this period.",
       "Harbor security is mentioned earlier; the final sentence is about winds."],
      ["monsoon"]),
    q("comparison",
      "Compared with overland Silk Road commerce, the trade described in the passage was more likely to involve",
      ["luxury goods of high value and low bulk",
       "heavier, lower-value bulk goods such as timber, grain and textiles",
       "trade conducted without any use of money or credit",
       "exchange limited to a single religious community"],
      1,
      ["Low-bulk luxuries were the specialty of expensive camel caravans.",
       "Correct. Ships could carry heavy, bulky cargoes that were uneconomic to move across Asia by land.",
       "Both networks used coinage, credit and bills of exchange.",
       "Indian Ocean trade crossed religious boundaries constantly."],
      ["monsoon", "silkroad"]));

  // ---------------- Unit 3 — Land-Based Empires (c. 1450 – c. 1750) ----------------

  set("u3s1", 3, st(
    "Paraphrase of a Mughal court chronicle describing the policies of the emperor Akbar, c. 1580.",
    "His Majesty has set aside the tax formerly collected from non-Muslims, and he has taken Rajput princesses into his household and given their kinsmen high rank and command. In the hall of worship he seats scholars of Islam, Brahmins, Jains, Zoroastrians and the Portuguese priests together, and listens while they dispute. Those who murmur against this say the faith is being diluted; His Majesty answers that the empire is wide and its peoples many."),
    q("purpose",
      "The policies described were most directly intended to",
      ["convert the empire's population to a single official religion",
       "consolidate authority over a religiously and ethnically diverse population",
       "transfer political power from the emperor to religious scholars",
       "end the Mughal practice of collecting land revenue"],
      1,
      ["Akbar's approach widened participation rather than enforcing one faith.",
       "Correct. Abolishing the jizya, marriage alliances and patronage of many traditions were tools of imperial consolidation.",
       "Debate was staged at the emperor's pleasure; authority stayed with him.",
       "Land revenue remained the backbone of Mughal finance."],
      []),
    q("comparison",
      "Which policy in another early modern empire is most similar in function to those described?",
      ["Ottoman administration of Christian and Jewish communities through their own religious leaders",
       "Tokugawa expulsion of European missionaries and restriction of foreign trade",
       "Spanish expulsion of Jews and Muslims from Iberia",
       "Safavid promotion of Twelver Shiism as the single state faith"],
      0,
      ["Correct. The millet arrangement likewise governed a diverse population by accommodating difference under imperial authority.",
       "That is a policy of exclusion, the opposite approach.",
       "Expulsion enforced religious uniformity rather than accommodating diversity.",
       "Safavid policy narrowed religious identity rather than broadening it."],
      ["japanclosed"]),
    q("cct",
      "Which later development represents the clearest change from the policies described in the passage?",
      ["The expansion of Mughal territory into the Deccan",
       "The reimposition of the tax on non-Muslims under Aurangzeb",
       "The continued employment of Hindu officials in Mughal service",
       "The construction of monumental tombs and mosques"],
      1,
      ["Expansion continued under several emperors and is not a reversal of religious policy.",
       "Correct. Aurangzeb's revival of the jizya reversed the accommodation described here.",
       "That is continuity, not change.",
       "Monumental building continued across reigns."],
      []));

  set("u3s2", 3, st(
    "Paraphrase of an Ottoman administrative memorandum on recruiting imperial servants, sixteenth century.",
    "Boys are taken from Christian villages of the Balkans, converted, schooled in Turkish and in the law, and set to serve. Some enter the palace and rise to the highest offices; the rest are trained to arms and paid from the treasury. Having no land of their own and no family of rank, they owe what they have to the Sultan alone. A man of noble birth serves his house first; such a man serves the Sultan first."),
    q("causation",
      "The practice described most directly strengthened the ruler by",
      ["creating an elite whose position depended on the sultan rather than on noble families",
       "replacing the standing army with mercenaries hired from Europe",
       "giving provincial landholders the right to collect taxes permanently",
       "transferring military command to elected village councils"],
      0,
      ["Correct. The devshirme produced soldiers and officials loyal to the ruler instead of to hereditary aristocracies.",
       "These recruits were the opposite of foreign mercenaries; they were raised in imperial service.",
       "Strengthening the center meant limiting, not entrenching, hereditary landholding claims.",
       "No such councils commanded Ottoman forces."],
      ["constantinople"]),
    q("comparison",
      "Which practice in another land-based empire served a most similar purpose?",
      ["Qing reliance on the Confucian examination system to recruit officials",
       "Safavid recruitment of enslaved Caucasians as soldiers and administrators answerable to the shah",
       "Russian granting of hereditary estates to boyar families",
       "Mughal collection of revenue through local zamindars"],
      1,
      ["Examinations recruited by learning, from families already established in Chinese society.",
       "Correct. Safavid ghulam troops and officials, like the janissaries, were an elite bound directly to the ruler.",
       "Hereditary estates strengthened exactly the kind of noble house these systems bypassed.",
       "Zamindars were existing local power holders, not a ruler-made elite."],
      []),
    q("process",
      "The memorandum is best used as evidence of which broader early modern development?",
      ["The decline of gunpowder weapons in Eurasian warfare",
       "The growth of centralized states with professional standing militaries",
       "The spread of representative assemblies limiting monarchs",
       "The abandonment of religious justification for imperial rule"],
      1,
      ["Gunpowder weaponry expanded in this period.",
       "Correct. Paid, trained, centrally controlled forces were a hallmark of early modern state building.",
       "Assemblies grew in parts of Europe, but that is not what this describes.",
       "Ottoman rule continued to be justified in religious terms."],
      []));

  // ---------------- Unit 4 — Transoceanic Interconnections (c. 1450 – c. 1750) ----------------

  set("u4s1", 4, st(
    "Rough estimates of where American silver ended up, 1550–1700. Figures are approximate and rounded, compiled for this practice set to show proportions only.",
    null,
    { kind: "table",
      head: ["Destination", "Approximate share of American silver"],
      rows: [["Europe (re-exported onward in large part)", "about two thirds"],
             ["Across the Pacific to Asia via Manila", "roughly a quarter"],
             ["Retained in the Americas", "a small remainder"],
             ["Ultimate resting place of a large share of all of it", "China"]] }),
    q("causation",
      "The pattern shown in the table was most directly driven by",
      ["Chinese demand for silver, which the Ming and Qing required for taxes and trade",
       "European refusal to trade with Asian merchants",
       "a Spanish ban on exporting silver from the Americas",
       "the absence of any market for silver outside the Americas"],
      0,
      ["Correct. China's silverized economy pulled bullion across both oceans, making silver the hinge of the first global trade.",
       "Europeans traded eagerly in Asia; silver was what they had to offer.",
       "Spain organized the export of silver rather than banning it.",
       "Demand for silver was enormous, above all in China."],
      ["potosi", "manila"]),
    q("process",
      "Which labor system most directly produced the silver described?",
      ["Wage labor recruited from Spanish cities",
       "Draft labor of Andean communities, building on an earlier Inca obligation",
       "Indentured servants brought from South Asia",
       "Monastic labor organized by the church"],
      1,
      ["Some paid workers existed, but the mines ran on coerced Andean labor.",
       "Correct. The colonial mita adapted an Inca labor draft to force Andean villagers into the Potosi mines.",
       "South Asian indenture belongs mainly to the nineteenth century.",
       "The church was deeply involved in colonization but did not supply the mine labor force."],
      ["potosi", "inca", "incafall"]),
    q("causation",
      "One significant long-term consequence of the silver flows shown was",
      ["the elimination of inflation across the Spanish empire",
       "the collapse of Indian Ocean trade networks",
       "sustained inflation in Europe and a Spanish economy dependent on bullion rather than manufacturing",
       "the end of European interest in Asian markets"],
      2,
      ["Silver inflows helped cause inflation rather than ending it.",
       "Indian Ocean trade intensified in this period.",
       "Correct. The influx pushed prices up and let Spain buy rather than build, with lasting economic effects.",
       "Interest in Asian markets grew as a result."],
      ["potosi", "manila"]));

  set("u4s2", 4, st(
    "Paraphrase of observations by a European naturalist on crops and animals moving between the hemispheres, c. 1600.",
    "In the gardens of Europe we now grow the maize and the knobbed root from Peru, which the poor plant where wheat will not thrive. In the Indies the Spaniards have set loose cattle, pigs and horses, which multiply beyond counting on the open grass. The native peoples of those lands, meanwhile, have been swept by smallpox and measles in numbers no war could match, and their fields lie empty."),
    q("causation",
      "The demographic catastrophe described in the final sentence most directly contributed to",
      ["the expansion of the Atlantic slave trade to replace lost labor",
       "the abandonment of European colonization in the Americas",
       "a rapid decline in European population",
       "the end of plantation agriculture in the Caribbean"],
      0,
      ["Correct. Catastrophic Indigenous mortality, together with plantation demand, drove the forced migration of millions of Africans.",
       "Colonization expanded rather than stopped.",
       "European populations grew in this period, helped by new American crops.",
       "Plantation agriculture expanded enormously."],
      ["smallpox", "slavetrade", "sugar"]),
    q("evidence",
      "The crops named in the first sentence are most significant for historians because they",
      ["raised caloric yields on poor land and helped drive population growth in Afro-Eurasia",
       "replaced rice as the staple food of East Asia",
       "were grown only as ornamental plants in Europe",
       "required irrigation systems that Europeans could not build"],
      0,
      ["Correct. Maize and the potato produced more calories on marginal land, underwriting Old World population increase.",
       "Rice remained the East Asian staple; maize and sweet potato supplemented it.",
       "They became field crops and staples, not mere ornaments.",
       "Both were grown widely without new irrigation works."],
      ["maize", "potato", "potatoeurope"]),
    q("cct",
      "The release of livestock described in the second sentence led over time to which change in the Americas?",
      ["The disappearance of Indigenous societies from the interior grasslands",
       "The adoption of horses by Indigenous nations, transforming hunting, warfare and mobility",
       "The end of bison herds within a single generation",
       "A shift of Indigenous agriculture toward wheat monoculture"],
      1,
      ["Interior nations adapted and in several cases grew more powerful.",
       "Correct. Plains nations built new horse-centered ways of life, a change driven by an animal the Columbian Exchange introduced.",
       "Bison were hunted to near extinction much later, in the nineteenth century.",
       "Indigenous farming continued to center on maize, beans and squash."],
      ["plainshorses", "horse", "exchange"]));

  // ---------------- Unit 5 — Revolutions (c. 1750 – c. 1900) ----------------

  set("u5s1", 5, st(
    "Paraphrase of a proclamation issued by revolutionary leaders in Saint-Domingue, c. 1801.",
    "We were told that all men are born free and equal in rights. We have taken those words at their word. The men who wrote them kept us in the cane fields and sold our children, and so we have taken our freedom with our own hands, and we will not return it. We ask the nations to trade with us as equals; we warn them that any fleet sent to restore the old order will find the island ready."),
    q("process",
      "The passage is best understood as evidence of which development in this period?",
      ["The rejection of Enlightenment thought by colonized peoples",
       "The use of Enlightenment claims about natural rights to attack slavery and colonial rule",
       "The spread of mercantilist economic theory",
       "The growth of divine-right justifications for monarchy"],
      1,
      ["The passage embraces those claims and turns them against their authors.",
       "Correct. Enslaved and colonized people pressed the logic of natural rights further than European revolutionaries had.",
       "Trade is mentioned, but the argument is about rights and freedom.",
       "The passage undercuts rather than supports monarchy."],
      ["haiti", "enlightenment", "frenchrev"]),
    q("causation",
      "Which combination best explains why this revolution occurred where it did?",
      ["A small enslaved population and a strong colonial garrison",
       "An enslaved majority on highly profitable sugar plantations, plus upheaval in the ruling metropole",
       "The absence of any plantation economy on the island",
       "A long tradition of representative government among colonists"],
      1,
      ["The enslaved majority was overwhelming, which is central to what happened.",
       "Correct. Saint-Domingue combined brutal, profitable sugar slavery with the political opening created by revolution in France.",
       "It was among the most profitable plantation colonies in the world.",
       "Colonial politics there was neither broadly representative nor stable."],
      ["haiti", "sugar", "frenchrev", "slavetrade"]),
    q("causation",
      "Which was a significant consequence of the revolution described?",
      ["Slaveholding powers isolated the new state diplomatically while abolitionists cited it as proof of possibility",
       "European powers immediately abolished slavery throughout their empires",
       "The sugar economy of the Caribbean ended within a decade",
       "France abandoned all territorial ambitions in the Americas until 1900"],
      0,
      ["Correct. Haiti faced embargo, indemnity and isolation, yet its victory reshaped debates over slavery everywhere.",
       "Abolition came decades later and unevenly.",
       "Sugar production continued elsewhere in the Caribbean, notably Cuba.",
       "France sold Louisiana soon after, but ambitions did not vanish for a century."],
      ["haiti", "louisiana"]));

  set("u5s2", 5, st(
    "Indicators of British industrial growth, 1750–1850. Approximate, rounded figures compiled for this practice set to show direction and scale only.",
    null,
    { kind: "table",
      head: ["Indicator", "c. 1750", "c. 1850"],
      rows: [["Raw cotton consumed per year", "a few million pounds", "hundreds of millions of pounds"],
             ["Coal output per year", "about 5 million tons", "about 60 million tons"],
             ["Population living in towns over 10,000", "roughly one in six", "roughly one in two"],
             ["Miles of railway open", "none", "several thousand"]] }),
    q("causation",
      "Which combination best explains why industrialization began in Britain rather than elsewhere?",
      ["Abundant coal and iron, navigable waterways, capital from overseas trade, and a productive agriculture",
       "A large standing army and a weak merchant class",
       "State ownership of all factories and mines",
       "Isolation from global trade networks"],
      0,
      ["Correct. These mutually reinforcing advantages are the standard explanation for Britain's early lead.",
       "Britain's merchant and financial sectors were unusually strong, not weak.",
       "Early British industry was overwhelmingly privately owned.",
       "Britain was deeply embedded in Atlantic and Asian trade."],
      ["steam", "mills", "oil"]),
    q("evidence",
      "The third row of the table is best used as evidence of",
      ["the decline of British agriculture into subsistence farming",
       "rapid urbanization as labor moved into factory towns",
       "the collapse of internal migration within Britain",
       "the spread of rural cottage industry at the expense of cities"],
      1,
      ["British agriculture became more productive, which is part of what freed labor.",
       "Correct. The shift from one in six to roughly half urban is a direct measure of industrial urbanization.",
       "Internal migration accelerated.",
       "Cottage industry contracted as factories concentrated production."],
      ["mills", "railway"]),
    q("comparison",
      "Industrialization in Japan and Russia later in the nineteenth century differed from the British pattern shown mainly in that it was",
      ["driven primarily by private entrepreneurs with no government involvement",
       "directed and financed heavily by the state as a strategic response to foreign pressure",
       "accomplished without railways or coal",
       "limited entirely to agricultural machinery"],
      1,
      ["State direction was the distinguishing feature in both cases.",
       "Correct. Meiji Japan and tsarist Russia industrialized through deliberate state investment under external pressure.",
       "Both built substantial railway networks.",
       "Both developed heavy industry, textiles and armaments."],
      ["meiji", "perry", "railway"]));

  // ---------------- Unit 6 — Consequences of Industrialization (c. 1750 – c. 1900) ----------------

  set("u6s1", 6, st(
    "Paraphrase of a speech to a European geographical society urging colonial expansion in Africa, c. 1885.",
    "The map of that continent is still open, and the nations that hesitate will find the best harbors and rivers taken. Our factories need cotton, palm oil and rubber, and our ships need coaling stations. Providence has placed the strong among the weak for a purpose: we bring the railway, the mission school and the rule of law, and in return we ask only the produce of the soil. Let the powers agree among themselves where each may act, so that Europeans need not fight Europeans."),
    q("purpose",
      "The final sentence most directly anticipates which development?",
      ["The agreement among European powers at the Berlin Conference to partition Africa among themselves",
       "The creation of the League of Nations mandate system",
       "The abolition of the Atlantic slave trade",
       "The independence of most African colonies"],
      0,
      ["Correct. The Berlin Conference set rules by which European states divided Africa without consulting Africans.",
       "The mandate system followed the First World War, decades later.",
       "The Atlantic trade had been legally abolished earlier in the century.",
       "Independence came in the mid-twentieth century."],
      ["africascramble"]),
    q("process",
      "The reasoning in the third sentence is the clearest example of",
      ["mercantilist trade theory",
       "an ideology of racial and civilizational hierarchy used to justify imperial rule",
       "a call for free trade without political control",
       "religious toleration as state policy"],
      1,
      ["Mercantilism concerns bullion and trade balances, not a providential hierarchy.",
       "Correct. Social Darwinist and civilizing-mission arguments framed conquest as duty.",
       "The speaker wants political control of harbors and territory.",
       "Mission schooling here serves empire rather than toleration."],
      ["africascramble"]),
    q("causation",
      "Which development most directly enabled Europeans to act on ambitions like those in the passage after 1850?",
      ["The invention of the printing press",
       "Steamships, quinine prophylaxis, the telegraph and rapid-firing weapons",
       "The replacement of sail by nuclear power",
       "The construction of the transcontinental railroad in North America"],
      1,
      ["Printing is far earlier and not the enabling factor here.",
       "Correct. River steamers, malaria prophylaxis, instant communication and machine guns made interior conquest feasible.",
       "Nuclear power belongs to the twentieth century.",
       "That railroad mattered for North America, not for African conquest."],
      ["suez", "africascramble", "yellowfever"]));

  set("u6s2", 6, st(
    "Patterns of long-distance migration, c. 1840–1910. Approximate, rounded orders of magnitude compiled for this practice set.",
    null,
    { kind: "table",
      head: ["Migration stream", "Rough scale", "Main destinations"],
      rows: [["Irish leaving Ireland after the famine", "millions", "United States, Britain, Australia"],
             ["Chinese emigrants, many on labor contracts", "millions", "Southeast Asia, Americas, Australia"],
             ["Indian indentured laborers", "well over a million", "Caribbean, Mauritius, Fiji, East and South Africa"],
             ["Europeans to the Americas overall", "tens of millions", "United States, Brazil, Argentina"]] }),
    q("causation",
      "The second and third streams in the table were driven most directly by",
      ["demand for plantation and mine labor after the abolition of slavery in European empires",
       "the refusal of European powers to permit any migration",
       "the collapse of global commodity prices",
       "state programs to settle Europeans in Asia"],
      0,
      ["Correct. Indenture and contract labor supplied plantations and mines once enslaved labor was legally ended.",
       "These migrations were organized within imperial systems, not forbidden.",
       "Commodity demand was rising, which is what pulled labor.",
       "These streams moved Asian labor outward, not Europeans inward."],
      ["slavetrade", "sugar"]),
    q("causation",
      "Which was a common consequence in receiving societies of the migrations shown?",
      ["The disappearance of ethnic enclaves within a generation",
       "Nativist political movements and restrictive laws targeting specific groups",
       "The immediate granting of full citizenship to all arrivals",
       "A decline in urban population growth"],
      1,
      ["Enclaves persisted and often became permanent communities.",
       "Correct. Exclusion acts and other restrictions followed, notably against Chinese migrants.",
       "Legal status was generally restricted, and often explicitly racialized.",
       "These migrations fed rapid urban growth."],
      ["irishus", "famine"]),
    q("cct",
      "Which effect in sending societies is most associated with heavily male labor migration in this period?",
      ["The end of agricultural production in home villages",
       "Women taking on expanded economic and household authority in the absence of men",
       "A rapid rise in birth rates in sending regions",
       "The replacement of remittances by colonial subsidies"],
      1,
      ["Production continued, largely through the labor of those who remained.",
       "Correct. With men away, women commonly managed land, trade and household decisions.",
       "Male absence tended to depress, not raise, birth rates.",
       "Remittances from migrants were a major income source."],
      ["famine"]));

  // ---------------- Unit 7 — Global Conflict (c. 1900 – present) ----------------

  set("u7s1", 7, st(
    "Paraphrase of a petition sent by colonial subjects to the victorious powers at the Paris peace conference, 1919.",
    "We fought in your trenches and carried your supplies; our villages sent grain and our young men did not return. You have declared that peoples shall decide their own government. We ask you to apply that principle to us. We are told instead that our lands will be administered by another power on our behalf, until such time as we are judged ready. We ask who is to be the judge, and by what right."),
    q("process",
      "The arrangement the petitioners object to in the fourth sentence is best identified as",
      ["the League of Nations mandate system",
       "the Marshall Plan",
       "the Berlin Conference partition",
       "the Warsaw Pact"],
      0,
      ["Correct. Mandates placed former Ottoman and German territories under other powers pending an undefined readiness.",
       "The Marshall Plan was post-1945 European reconstruction aid.",
       "Berlin was 1884-85 and concerned Africa specifically.",
       "The Warsaw Pact was a Cold War military alliance."],
      ["versailles", "ww1"]),
    q("causation",
      "The first sentence points to which significant consequence of the First World War for colonized peoples?",
      ["Wartime service and sacrifice strengthened demands for self-rule after the war",
       "Colonial populations were excluded from the war effort entirely",
       "Colonies gained immediate independence in 1919",
       "Colonial economies were unaffected by the war"],
      0,
      ["Correct. Mass participation in a total war gave independence movements a powerful moral and political claim.",
       "Millions of colonial subjects served or supplied the war effort.",
       "Independence for most came after the Second World War.",
       "Colonial economies were reorganized for war and strained heavily."],
      ["ww1", "india", "gandhisa"]),
    q("causation",
      "The economic collapse that began in 1929 most directly contributed to which political development of the 1930s?",
      ["The broad expansion of parliamentary democracy across Europe",
       "The rise of authoritarian and fascist movements promising recovery and national renewal",
       "The end of colonial empires in Asia and Africa",
       "The abolition of tariffs and creation of free trade worldwide"],
      1,
      ["Several democracies failed under the strain of the Depression.",
       "Correct. Mass unemployment and discredited liberal governments created openings exploited by authoritarian movements.",
       "Decolonization came later, though the Depression strained empires.",
       "States raised tariffs sharply in the 1930s."],
      ["depression", "nazis"]));

  set("u7s2", 7, st(
    "Paraphrase of an official explanation given to a Japanese domestic audience for expansion in Asia, c. 1940.",
    "Our islands have little iron, less oil and no rubber, and those who hold these things have shown they will withhold them. A sphere of co-prosperity under our guidance will free Asia from Western rule and supply what our industry requires. Those who resist within that sphere resist the liberation of Asia itself."),
    q("sourcing",
      "A historian would most likely use this passage as evidence of",
      ["the actual popularity of Japanese rule among occupied populations",
       "how an expansionist state framed conquest as both strategic necessity and liberation",
       "the absence of resource motives in Japanese policy",
       "a Japanese decision to withdraw from continental Asia"],
      1,
      ["The passage reveals official claims, not the experience of occupied peoples, which was often brutal.",
       "Correct. It shows resource anxiety and anti-Western liberation rhetoric bundled into one justification.",
       "Resources are the passage's opening argument.",
       "It argues for expansion, not withdrawal."],
      ["ww2", "pearlharbor"]),
    q("process",
      "Which feature of twentieth-century warfare is best illustrated by the reasoning in the first sentence?",
      ["Total war, in which industrial capacity and raw materials determine strategy",
       "Limited dynastic warfare fought by small professional armies",
       "Warfare conducted without regard to economic resources",
       "The replacement of state armies by private mercenary companies"],
      0,
      ["Correct. Industrial war made oil, iron and rubber strategic objectives in their own right.",
       "That describes early modern European warfare.",
       "Resources are precisely the concern expressed.",
       "States mobilized national armies and economies."],
      ["ww2", "oil"]),
    q("causation",
      "The use of atomic weapons in 1945 most directly contributed to which later development?",
      ["The end of all great-power military competition",
       "A nuclear arms race and a Cold War strategy built on deterrence",
       "The immediate unification of Germany",
       "The abandonment of rocket research by major powers"],
      1,
      ["Competition intensified, though it avoided direct great-power war.",
       "Correct. Nuclear arsenals and deterrence shaped superpower conflict for decades.",
       "Germany was divided for over forty years.",
       "Rocket research expanded rapidly into missiles and spaceflight."],
      ["hiroshima", "v2", "sputnik"]));

  // ---------------- Unit 8 — Cold War and Decolonization (c. 1900 – present) ----------------

  set("u8s1", 8, st(
    "Paraphrase of a speech by a newly independent Asian head of government to a conference of African and Asian states, c. 1955.",
    "We did not win our freedom in order to hire it out again. We are told we must choose a side, and that whoever does not choose is an enemy of both. We refuse the question. We will take technical help from any country that offers it without conditions on our politics, we will trade where trade is fair, and we will speak for the peoples still under colonial rule. There are more of us than there are of them."),
    q("purpose",
      "The speaker's position is best identified as",
      ["membership in the North Atlantic alliance",
       "non-alignment between the Cold War blocs",
       "support for the restoration of colonial administration",
       "advocacy of world government under the superpowers"],
      1,
      ["The speech explicitly refuses alliance with either bloc.",
       "Correct. This is the classic non-aligned position articulated at Bandung and after.",
       "The speech champions the end of colonial rule.",
       "It asserts the independence of newly free states against superpower direction."],
      ["india", "ghana", "un"]),
    q("causation",
      "Which development most directly made the conference described possible?",
      ["The weakening of European empires by the Second World War and the wave of independence that followed",
       "The expansion of European colonial rule after 1945",
       "The unification of Asia and Africa into a single federation",
       "The collapse of the Soviet Union"],
      0,
      ["Correct. Exhausted metropoles and successful independence movements created a bloc of new states able to meet as equals.",
       "Empires contracted sharply after 1945.",
       "No such federation existed; these were sovereign states cooperating.",
       "The Soviet collapse came in 1991, decades later."],
      ["ww2", "india", "ghana"]),
    q("comparison",
      "Compared with the states represented at this conference, countries such as South Korea and Poland in the same decade",
      ["pursued identical policies of non-alignment",
       "were firmly embedded in a superpower bloc, with their security and economies tied to it",
       "had no formal governments",
       "were still formally colonies of European powers"],
      1,
      ["Both were aligned, not non-aligned.",
       "Correct. Bloc membership tied their militaries, trade and in some cases domestic politics to a superpower.",
       "Both had functioning states.",
       "Neither was a European colony in the 1950s."],
      ["berlinwall", "prc"]));

  set("u8s2", 8, st(
    "Paraphrase of a letter from an anti-colonial organizer describing strategy, c. 1930.",
    "They have the rifles, so we will not meet them with rifles. We will break the law that taxes the salt of the sea and we will break it in the open, in front of their photographers, and we will accept the prison that follows. Let the world read what is done to people who have raised no hand. A government that must beat the unarmed to keep a tax will not keep it long."),
    q("process",
      "The strategy described is best identified as",
      ["guerrilla warfare against military targets",
       "mass nonviolent civil disobedience designed to expose the violence of the state",
       "negotiation conducted privately among elites",
       "a general strike by industrial trade unions"],
      1,
      ["The passage rules out armed confrontation.",
       "Correct. Deliberate, public, documented lawbreaking with acceptance of punishment is the core of this method.",
       "Publicity before photographers is the opposite of private negotiation.",
       "Strikes were used in this era, but the action described is breaking a specific law."],
      ["saltmarch", "thoreau"]),
    q("causation",
      "The method described directly influenced which later movements?",
      ["The American civil rights movement and the campaign against apartheid in South Africa",
       "The Bolshevik seizure of power in Russia",
       "The unification of Germany under Bismarck",
       "The Meiji Restoration in Japan"],
      0,
      ["Correct. Organizers in Montgomery and in South Africa studied and adapted these tactics explicitly.",
       "The Bolsheviks pursued armed revolution.",
       "German unification was achieved by war and diplomacy.",
       "The Meiji Restoration preceded this by decades."],
      ["saltmarch", "montgomery", "mandela"]),
    q("evidence",
      "Which postwar development gave movements like this additional international leverage?",
      ["The adoption of the Universal Declaration of Human Rights and the growth of global media coverage",
       "The creation of the gold standard",
       "The signing of the Treaty of Versailles",
       "The establishment of the Berlin Conference rules"],
      0,
      ["Correct. Shared human-rights language plus worldwide publicity raised the diplomatic cost of repression.",
       "The gold standard is an unrelated monetary arrangement.",
       "Versailles preceded this and largely denied colonial claims.",
       "Berlin Conference rules served partition, not anti-colonial movements."],
      ["udhr", "mandela", "un"]));

  // ---------------- Unit 9 — Globalization (c. 1900 – present) ----------------

  set("u9s1", 9, st(
    "Atmospheric carbon dioxide measured at Mauna Loa, selected years. Values are rounded parts per million; the long record is known as the Keeling curve.",
    null,
    { kind: "table",
      head: ["Year", "CO2 (parts per million, approximate)"],
      rows: [["1958", "about 315"], ["1980", "about 339"], ["2000", "about 369"], ["2020", "about 414"], ["2024", "about 424"]] }),
    q("causation",
      "The trend shown is most directly attributed by scientists to",
      ["volcanic eruptions in the twentieth century",
       "the sustained combustion of fossil fuels together with land-use change",
       "a natural cycle unrelated to human activity",
       "the growth of nuclear power generation"],
      1,
      ["Volcanic emissions are small compared with fossil fuel emissions.",
       "Correct. Coal, oil and gas combustion plus deforestation account for the rise.",
       "The rate and isotopic signature of the rise point to human sources.",
       "Nuclear generation produces little carbon dioxide."],
      ["keeling", "steam", "oil", "car"]),
    q("cct",
      "The data are best used as evidence for which continuity across the modern period?",
      ["Continued reliance on fossil-fuel energy first established during industrialization",
       "The persistence of subsistence agriculture as the dominant world economy",
       "The continuity of pre-industrial transportation systems",
       "Unchanging global population since 1900"],
      0,
      ["Correct. The curve measures the ongoing consequence of an energy regime begun in the industrial revolution.",
       "Industrial and service economies dominate global output.",
       "Transportation changed radically across this period.",
       "World population grew roughly fourfold since 1900."],
      ["steam", "mills", "oil"]),
    q("process",
      "Which response to the pattern shown is most characteristic of the late twentieth and early twenty-first centuries?",
      ["Unilateral action by single states acting alone",
       "Negotiated international agreements setting emissions commitments",
       "Abandonment of scientific monitoring",
       "Transfer of environmental policy to private corporations alone"],
      1,
      ["States acted, but the characteristic form was multilateral negotiation.",
       "Correct. Frameworks from Rio to Kyoto to the Paris Agreement are the signature response.",
       "Monitoring expanded substantially.",
       "Corporate action exists, but policy has been made chiefly by states and international bodies."],
      ["paris", "earthday", "keeling"]));

  set("u9s2", 9, st(
    "Paraphrase of a retrospective account by an engineer who worked on early computer networks.",
    "The money came from a defense agency that wanted communication to survive damage, and so we built a network with no center. We were not thinking about shopping or about strangers arguing; we were thinking about whether a message could find another route. Once universities were connected, the traffic we had not planned for — mail, lists, arguments — became most of the traffic. Later someone put a simple document system on top of it and the public arrived."),
    q("causation",
      "The sequence described is the best illustration of which pattern?",
      ["Military and state research funding producing technologies later transformed by civilian use",
       "Private consumer demand driving all technological innovation",
       "Scientific research proceeding without institutional funding",
       "Technology transfer from colonies to metropoles"],
      0,
      ["Correct. Defense funding built the network; unplanned civilian uses then redefined it.",
       "Consumer demand shaped later stages, not the origin.",
       "The account stresses that funding came from a state agency.",
       "No colonial transfer is involved."],
      ["arpa", "arpanet", "www", "sputnik"]),
    q("causation",
      "Which later development is the clearest consequence of the 'document system' mentioned in the final sentence?",
      ["The decline of global trade in the 1990s",
       "Mass public access to information and the use of networks to organize political movements",
       "The end of state censorship everywhere",
       "The replacement of all printed books within a decade"],
      1,
      ["Global trade expanded in this period.",
       "Correct. The web opened the network to the public and became infrastructure for protest and organization.",
       "Many states built extensive censorship and surveillance systems.",
       "Print persisted alongside digital media."],
      ["www", "smartphone", "arabspring"]),
    q("comparison",
      "The spread described is most comparable to which earlier development?",
      ["The printing press, which cut the cost of copying and spread ideas faster than authorities could control",
       "The invention of the wheel, which chiefly affected overland haulage",
       "The adoption of the gold standard, which standardized currencies",
       "The building of the Suez Canal, which shortened a shipping route"],
      0,
      ["Correct. Both collapsed the cost of reproducing and circulating text, with comparable disruptive effects on authority.",
       "The wheel is a transport technology, a weaker analogy for information.",
       "Monetary standardization is not an information technology.",
       "Canals shorten routes; they do not multiply copies of ideas."],
      ["gutenberg", "www", "luther"]));

  set("u9s3", 9, st(
    "Paraphrase of a World Health Organization field report on the final stage of the smallpox eradication campaign, c. 1977.",
    "The last chains of transmission were broken not by mass vaccination of whole countries but by finding each case, vaccinating everyone around it, and watching. This required health workers who could cross borders, cold boxes that kept vaccine viable in heat, and governments on both sides of a conflict agreeing to let teams pass."),
    q("causation",
      "The campaign described was made possible chiefly by",
      ["international cooperation through a global health organization, sustained across political divisions",
       "the invention of the first vaccine during the campaign itself",
       "the closing of all international borders to travel",
       "a single country acting alone"],
      0,
      ["Correct. Eradication required coordinated surveillance, logistics and cross-border access organized internationally.",
       "Vaccination against smallpox dated from the late eighteenth century.",
       "The campaign depended on teams being able to cross borders.",
       "No single state could have interrupted transmission everywhere."],
      ["who", "jenner", "un"]));

  // ---------------- Section I Part B — Short Answer Questions ----------------
  // Real exam: answer Question 1 and 2, then choose Question 3 OR Question 4. 40 minutes.

  SAQ.push({
    id: "saq1", required: true, kind: "Secondary source",
    stim: st("Paraphrase of two historians' competing interpretations of Indian Ocean trade before 1450.",
      "Historian A argues that the Indian Ocean world functioned as a single commercial system long before Europeans entered it, held together by monsoon winds, shared commercial law among merchants and resident trading communities, with no single state in control.\nHistorian B argues that calling it one system overstates the case: the ocean held several overlapping regional circuits, each dominated by different ports and rulers, and what looks unified from a distance was in practice a chain of separate markets."),
    parts: [
      { label: "a", prompt: "Describe one difference between Historian A's and Historian B's interpretations of Indian Ocean trade." },
      { label: "b", prompt: "Explain how one specific piece of historical evidence from the period c. 1200 to c. 1450 could be used to support Historian A's interpretation." },
      { label: "c", prompt: "Explain how one specific piece of historical evidence from the period c. 1200 to c. 1450 could be used to support Historian B's interpretation." }],
    guide: [
      ["A sees one integrated system; B sees several overlapping regional circuits.",
       "A stresses shared practices and no central state; B stresses local rulers dominating separate markets."],
      ["Shared reliance on monsoon winds set a single seasonal rhythm from East Africa to China.",
       "Diasporic merchant communities (Gujarati, Arab, Chinese, Swahili) lived in ports across the whole ocean.",
       "Common commercial instruments and credit practices let merchants deal across political borders.",
       "Goods such as Indian cotton textiles circulated ocean-wide, from Africa to Southeast Asia."],
      ["Malacca, Kilwa, Calicut and Quanzhou each dominated a distinct regional circuit with its own ruler and tolls.",
       "Rulers taxed and regulated their own harbors independently, with no ocean-wide authority.",
       "Different segments used different ships and routes, with goods transferred between circuits at entrepots.",
       "Chinese state voyages under Zheng He operated on their own terms rather than within one commercial system."]],
    atlas: ["monsoon", "malacca", "zhenghe", "zimbabwe"] });

  SAQ.push({
    id: "saq2", required: true, kind: "Primary source",
    stim: st("Paraphrase of a petition from weavers in an industrializing British town to Parliament, c. 1812.",
      "We learned our trade over seven years and worked in our own homes, setting our own hours, and we fed our families by it. Now a single engine-driven frame in a mill does the work of many hands, tended by children who are paid in pence. We do not ask that the machines be destroyed. We ask that a man who has given his life to a trade not be thrown on the parish, and that there be some rule about the hours a child may be kept at the frame."),
    parts: [
      { label: "a", prompt: "Identify one change in the organization of work that the petitioners describe." },
      { label: "b", prompt: "Explain one historical situation in the period 1750 to 1900 that led to the change the petitioners describe." },
      { label: "c", prompt: "Explain one way that workers in the nineteenth century responded to conditions like those described in the source." }],
    guide: [
      ["Production moved from skilled work at home to machine-tended work in mills.",
       "Skilled adult artisans were displaced by cheaper child labor.",
       "Workers lost control over their own hours and pace of work."],
      ["Mechanization of textile spinning and weaving, powered first by water and then by steam.",
       "Britain's coal, capital and agricultural productivity enabled factory production.",
       "Growing demand for cheap cotton cloth in domestic and imperial markets.",
       "Enclosure and rural change pushed labor toward industrial towns."],
      ["Forming trade unions and mutual aid societies, and pressing for legal limits on hours and child labor.",
       "Machine breaking and other direct action, as in the Luddite protests.",
       "Strikes and petitions to Parliament; later, mass movements such as Chartism.",
       "Support for socialist and reform parties seeking state regulation of industry."]],
    atlas: ["mills", "steam", "cottongin"] });

  SAQ.push({
    id: "saq3", required: false, choiceGroup: "3or4", window: "c. 1200 – c. 1750",
    stim: null,
    parts: [
      { label: "a", prompt: "Identify one way that land-based empires in the period 1450 to 1750 legitimized their rule." },
      { label: "b", prompt: "Explain one way that land-based empires in this period administered and taxed their territories." },
      { label: "c", prompt: "Explain one similarity OR one difference between how two land-based empires of this period maintained power." }],
    guide: [
      ["Monumental architecture such as the Taj Mahal, Versailles or Ottoman mosque complexes.",
       "Religious claims: divine right, the Safavid shah as Shia authority, the Ottoman sultan as caliph.",
       "Court ritual, patronage of art and learning, and official histories.",
       "Claims of descent, such as Mughal or Timurid lineage."],
      ["Tax farming in the Ottoman Empire; the zamindar system in Mughal India.",
       "Salaried appointed officials recruited by examination in Qing China.",
       "Land grants tied to military service, such as Mughal mansabdars or Ottoman timars.",
       "Census and land surveys to assess revenue."],
      ["Similarity: both Ottomans and Safavids used elites recruited from outside hereditary nobilities.",
       "Similarity: both Mughal and Ottoman rulers accommodated religious diversity to govern plural populations.",
       "Difference: Qing officials were recruited by examination, while Mughal mansabdars held land grants for military service.",
       "Difference: Safavids enforced one state religion, while Mughals under Akbar accommodated many."]],
    atlas: ["constantinople", "qin"] });

  SAQ.push({
    id: "saq4", required: false, choiceGroup: "3or4", window: "c. 1750 – present",
    stim: null,
    parts: [
      { label: "a", prompt: "Identify one cause of decolonization in the period after 1900." },
      { label: "b", prompt: "Explain one method used by an independence movement in this period to achieve its goals." },
      { label: "c", prompt: "Explain one challenge faced by a newly independent state after achieving independence." }],
    guide: [
      ["The two world wars exhausted European imperial powers militarily and financially.",
       "Colonial subjects' wartime service strengthened claims to self-rule.",
       "The global spread of nationalism and of self-determination rhetoric.",
       "Cold War superpower competition made overt colonialism harder to sustain."],
      ["Mass nonviolent civil disobedience, as in the Indian independence movement.",
       "Armed struggle, as in Algeria or Vietnam.",
       "Negotiated transfer of power following elections and sustained political organizing, as in Ghana.",
       "International pressure through the United Nations and world opinion."],
      ["Borders drawn by colonial powers that cut across communities, fueling conflict.",
       "Partition and mass displacement, as in India and Pakistan in 1947.",
       "Economies built to export a single commodity, leaving them vulnerable.",
       "Pressure to align with a Cold War bloc; coups and proxy conflict.",
       "Shortages of trained administrators, teachers and doctors at independence."]],
    atlas: ["india", "ghana", "mandela", "un"] });

  // ---------------- Section II Part A — Document-Based Question ----------------

  const DBQ = {
    id: "dbq1",
    window: "1450–1750",
    prompt: "Evaluate the extent to which the exchange of goods, crops, people and diseases across the Atlantic and Pacific transformed societies in the period 1450 to 1750.",
    note: "All seven documents are paraphrases or adapted summaries written for this practice set. Use them as you would real documents: read the source line as carefully as the text.",
    docs: [
      { n: 1, source: "A Spanish colonial official reporting to the crown on the silver mines of Potosi, c. 1585. Paraphrased.",
        body: "Each year the villages of the highlands must send one in seven of their men to the mines, as was the custom of the Inca before us, and we have only continued it for the service of His Majesty. The mountain yields as no mine in Europe yields. I must report that many who go do not return, that their fields go unplanted, and that the curacas beg to be released from the quota. Yet without this labor the fleets will sail empty." },
      { n: 2, source: "Testimony of Nahua elders in central Mexico, recorded decades after the epidemic of 1520. Paraphrased.",
        body: "The sickness came when the strangers came. It spread over us, and great sores broke out on our faces and our bodies. We could not walk; we lay on our beds like corpses. Many died of hunger because there was no one well enough to bring food. Those who lived were pitted and some were blind. The warriors could not stand; this is how the city was taken." },
      { n: 3, source: "Letter from King Afonso I of Kongo to the king of Portugal, 1526. Paraphrased.",
        body: "Your merchants land here daily and carry off our people. They take noblemen and the sons of noblemen, even our own relatives. They seize free men and brand them and put them on ships, so that our land is becoming empty of its inhabitants. We welcomed your priests and your goods; we did not ask for this. We beg you to send no more merchants and no more goods, only priests and schoolmasters." },
      { n: 4, source: "A Ming dynasty official's memorial on currency and taxation, c. 1590. Paraphrased.",
        body: "The people no longer bring grain or cloth to the tax office; they bring silver, and the treasury demands silver. Silver comes in ships from Luzon, brought by foreigners who want our silk and our porcelain and have nothing else we lack. When the ships are late the price of silver rises and the poor cannot pay their taxes, though their harvest was the same as the year before." },
      { n: 5, source: "An English writer on husbandry, discussing a new root crop, c. 1690. Paraphrased.",
        body: "The root from the Indies will grow where wheat will not, on thin and stony ground, and yields more food from an acre than any grain. The gentry will not eat it, calling it fit only for swine and the Irish. Yet I have seen a family of six kept alive through a hard winter by a plot no bigger than a garden, and I judge that in time it will feed more of the poor of Europe than bread does." },
      { n: 6, source: "Estimated arrivals of enslaved Africans in the Americas, by destination region, to 1750. Approximate, rounded figures compiled for this practice set.",
        body: null, kind: "table",
        head: ["Destination", "Approximate share of arrivals to 1750"],
        rows: [["Brazil", "roughly a third"], ["Caribbean (British, French, Dutch, Spanish)", "roughly a half"], ["Spanish mainland America", "under a tenth"], ["British North America", "a small fraction"]] },
      { n: 7, source: "A Jesuit missionary in south China writing to his superior, c. 1640. Paraphrased.",
        body: "In the hills where rice cannot be flooded, the farmers now plant the American grain with the great ears, and a sweet root also from those lands. Families who had no land worth the name are settling the slopes and the land is filling with people. The officials approve because the new fields pay tax. I note this because it shows how God's providence may arrive in a seed." }],
    rubric: [
      { pts: 1, name: "Thesis or claim", ask: "A historically defensible claim that establishes a line of reasoning — not a restatement of the prompt. One or more sentences in one place, intro or conclusion.",
        check: ["My thesis makes an evaluative claim about HOW MUCH societies were transformed, not just that they were.", "My thesis previews a line of reasoning (at least two distinct supporting strands)."] },
      { pts: 1, name: "Contextualization", ask: "Describe a broader historical context relevant to the prompt — developments before, during or after, beyond a passing phrase.",
        check: ["I describe context beyond one sentence of throat-clearing (e.g. pre-1450 Afro-Eurasian trade networks, or state-building and maritime technology before 1492)."] },
      { pts: 2, name: "Evidence from the documents", ask: "1 point: accurately describe the content of at least three documents. 2 points: use the content of at least six documents to support the argument in response to the prompt.",
        check: ["I use at least six documents, and each one supports my argument rather than being summarized in isolation.", "I cite documents by number or by clear reference."] },
      { pts: 1, name: "Evidence beyond the documents", ask: "Use one specific, relevant piece of historical evidence not found in the documents, beyond a mere mention.",
        check: ["My outside evidence is specific (a named development, person, policy or technology) and I explain how it supports my argument."] },
      { pts: 1, name: "Sourcing analysis", ask: "For at least three documents, explain how or why the point of view, purpose, situation and/or audience is relevant to the argument.",
        check: ["For three documents I explain WHY the source's position shapes what it says, and tie that to my argument."] },
      { pts: 1, name: "Complexity", ask: "Demonstrate a complex understanding — corroborate, qualify or modify an argument, analyze multiple variables, or explain both similarity and difference, continuity and change, or cause and effect.",
        check: ["I show transformation was uneven — e.g. catastrophic in the Americas, population-raising in Afro-Eurasia, selectively disruptive in China — and I sustain that complexity, not just mention it."] }],
    outside: ["The Manila galleon route tying Acapulco silver to Chinese markets from 1571.",
      "The encomienda system and its replacement by other forms of coerced labor.",
      "Plantation monoculture of sugar in Brazil and the Caribbean, and its labor demands.",
      "The spread of maize and cassava in West and Central Africa.",
      "Syncretic religions formed in the Americas, such as Vodun practice or the cult of the Virgin of Guadalupe.",
      "Joint-stock companies such as the Dutch and English East India Companies.",
      "The Great Dying and its demographic scale in the Americas.",
      "Resistance: maroon communities, the Pueblo Revolt of 1680, Queen Nzinga's campaigns."],
    atlas: ["exchange", "smallpox", "potosi", "manila", "slavetrade", "sugar", "potatoeurope", "maize", "aztecfall", "incafall"] };

  // ---------------- Section II Part B — Long Essay Question ----------------

  const LEQ_RUBRIC = [
    { pts: 1, name: "Thesis or claim", ask: "A historically defensible claim establishing a line of reasoning, in one place (intro or conclusion).",
      check: ["My thesis answers the question asked with an evaluative claim, and previews a line of reasoning."] },
    { pts: 1, name: "Contextualization", ask: "Describe a broader historical context relevant to the prompt.",
      check: ["I describe relevant context beyond a single sentence, and connect it to the prompt."] },
    { pts: 2, name: "Evidence", ask: "1 point: two specific relevant examples. 2 points: use that evidence to support an argument in response to the prompt.",
      check: ["I give at least two specific examples (named, dated, located).", "I explain how each example supports my argument rather than listing it."] },
    { pts: 2, name: "Analysis and reasoning", ask: "1 point: use historical reasoning (comparison, causation, continuity and change) to frame the argument. 2 points: demonstrate a complex understanding.",
      check: ["My essay is organized by the reasoning process the prompt asks for.", "I complicate my own argument — counter-evidence, a qualification, or an explanation of uneven effects — and sustain it."] }];

  LEQ.push({ id: "leq1", option: 1, window: "c. 1200 – c. 1450",
    prompt: "Develop an argument that evaluates the extent to which trade networks changed societies in Afro-Eurasia in the period c. 1200 to c. 1450.",
    evidence: ["Mongol control of overland routes and the security of caravan trade", "Monsoon-based Indian Ocean commerce and diasporic merchant communities",
      "Trans-Saharan gold and salt trade and the growth of Mali and Timbuktu", "Transfer of papermaking, gunpowder and numerals across Eurasia",
      "Spread of the Black Death along the same routes", "Growth of port cities such as Malacca, Kilwa, Calicut and Quanzhou",
      "Champa rice and agricultural change in southern China"],
    atlas: ["silkroad", "monsoon", "genghis", "mansamusa", "blackdeath", "malacca", "papersamarkand"] });

  LEQ.push({ id: "leq2", option: 2, window: "c. 1450 – c. 1900",
    prompt: "Develop an argument that evaluates the extent to which states' demand for labor shaped societies in the period c. 1450 to c. 1900.",
    evidence: ["The mita labor draft and silver production at Potosi", "Encomienda and hacienda systems in Spanish America",
      "The Atlantic slave trade and plantation economies in Brazil and the Caribbean", "Serfdom in Russia and its persistence into the nineteenth century",
      "Abolition and the turn to indentured labor from India and China", "Factory labor, child labor and union organizing in industrializing states",
      "Resistance: maroon communities, slave revolts, the Haitian Revolution"],
    atlas: ["potosi", "slavetrade", "sugar", "haiti", "mills", "famine"] });

  LEQ.push({ id: "leq3", option: 3, window: "c. 1750 – present",
    prompt: "Develop an argument that evaluates the extent to which technological change caused political change in the period c. 1750 to the present.",
    evidence: ["Steam power, railways and the reorganization of states and empires", "Steamships, quinine and rapid-firing weapons in the new imperialism",
      "Industrial warfare in the world wars and the rise of total mobilization", "Nuclear weapons and Cold War deterrence",
      "Radio, television and mass propaganda", "Computer networks, the web and smartphones in recent protest movements",
      "Medical technology, vaccination campaigns and the authority of international health bodies"],
    atlas: ["steam", "railway", "africascramble", "ww1", "hiroshima", "www", "smartphone", "arabspring", "who"] });

  // ---------------- Course metadata, weighting and the (unofficial) curve ----------------

  window.AP = {
    course: "AP World History: Modern",
    unofficial: "Unofficial practice kit. Not affiliated with or endorsed by the College Board. All stimuli are original paraphrases written for this project.",
    units: [
      { n: 1, title: "The Global Tapestry", span: "c. 1200 – c. 1450" },
      { n: 2, title: "Networks of Exchange", span: "c. 1200 – c. 1450" },
      { n: 3, title: "Land-Based Empires", span: "c. 1450 – c. 1750" },
      { n: 4, title: "Transoceanic Interconnections", span: "c. 1450 – c. 1750" },
      { n: 5, title: "Revolutions", span: "c. 1750 – c. 1900" },
      { n: 6, title: "Consequences of Industrialization", span: "c. 1750 – c. 1900" },
      { n: 7, title: "Global Conflict", span: "c. 1900 – present" },
      { n: 8, title: "Cold War and Decolonization", span: "c. 1900 – present" },
      { n: 9, title: "Globalization", span: "c. 1900 – present" }],
    skills: {
      process: "Developments and processes",
      sourcing: "Sourcing and situation",
      evidence: "Claims and evidence in sources",
      purpose: "Purpose, point of view and audience",
      contextualization: "Contextualization",
      comparison: "Making connections: comparison",
      causation: "Making connections: causation",
      cct: "Making connections: continuity and change",
    },
    sections: [
      { id: "mcq", name: "Section I, Part A", label: "Multiple choice", count: 55, minutes: 55, weight: 0.40 },
      { id: "saq", name: "Section I, Part B", label: "Short answer", count: 3, minutes: 40, weight: 0.20 },
      { id: "dbq", name: "Section II, Part A", label: "Document-based question", count: 1, minutes: 60, weight: 0.25, reading: 15 },
      { id: "leq", name: "Section II, Part B", label: "Long essay", count: 1, minutes: 40, weight: 0.15 }],
    // Approximate score bands. The real curve is set each year and is not published in advance.
    curve: [{ min: 0.70, score: 5 }, { min: 0.57, score: 4 }, { min: 0.43, score: 3 }, { min: 0.28, score: 2 }, { min: 0, score: 1 }],
    MCQ, SAQ, DBQ, LEQ, LEQ_RUBRIC,
  };
})();
