// Butterfly Atlas data. To add history, add an ev(...) row and link it with ln(...).
// ev(id, year, title, place, lat, lon, kind, sentence, {ca: true} if the date is approximate, {when: "..."} to override the label)
// ln(fromId, toId, "why the first thing helped cause the second")
// Years before the common era are negative: -500 means 500 BCE.
// Kinds: food, trade, ideas, science, power, rights, health, planet, people

(function () {
  const EVENTS = [];
  const LINKS = [];
  const ev = (id, y, t, p, lat, lon, k, s, o = {}) => EVENTS.push({ id, y, t, p, lat, lon, k, s, ...o });
  const ln = (from, to, why) => LINKS.push({ from, to, why });
  const ca = { ca: true };

  // ---------- Deep past ----------
  ev("australia", -10000, "Aboriginal Australians", "Australia", -25, 134, "rights", "People have lived in Australia for at least 50,000 years, one of the oldest living cultures on Earth.", { when: "50,000+ years ago" });
  ev("farming", -9000, "The first farms", "Fertile Crescent", 35.5, 40, "food", "People began planting wheat and barley instead of only hunting and gathering.", ca);
  ev("rice", -7000, "Rice farming", "Yangtze River, China", 30, 112, "food", "Farmers along the Yangtze River learned to grow rice in wet fields.", ca);
  ev("maize", -7000, "Maize (corn) is tamed", "Southern Mexico", 18, -99, "food", "Farmers turned a skinny wild grass called teosinte into corn, bit by bit over generations.", ca);
  ev("potato", -6000, "Potatoes are farmed", "Andes Mountains", -15, -70, "food", "People high in the Andes grew potatoes, which survive cold and thin air.", ca);
  ev("cities", -3500, "The first cities", "Uruk, Mesopotamia", 31.3, 45.6, "power", "Uruk grew to tens of thousands of people, with temples, workshops and walls.", ca);
  ev("wheel", -3500, "The wheel", "Mesopotamia & Europe", 44, 34, "science", "Wheels appeared on carts, and on potters' wheels, making heavy loads and pots easier to move and make.", ca);
  ev("writing", -3200, "Writing is invented", "Uruk, Mesopotamia", 31.6, 46.2, "ideas", "People pressed marks into clay to keep track of grain, sheep and debts. Egypt began writing at about the same time.", ca);
  ev("caral", -2600, "Caral, first city of the Americas", "Peru", -10.9, -77.5, "power", "People in Caral built pyramids and plazas at the same time Egypt built its pyramids.", ca);
  ev("indus", -2600, "Cities of the Indus", "Mohenjo-daro, Pakistan", 27.3, 68.1, "power", "Indus cities had straight streets, brick houses and drains, well planned for their time.", ca);
  ev("pyramid", -2560, "The Great Pyramid", "Giza, Egypt", 30, 31.1, "power", "Egyptian workers stacked over two million stone blocks into a tomb for King Khufu.", ca);
  ev("horse", -2200, "Horses are tamed", "Eurasian steppe", 48, 42, "food", "Herders on the grasslands tamed the horses that almost all riding horses today come from.", ca);
  ev("hammurabi", -1754, "Hammurabi's laws", "Babylon", 32.5, 44.4, "rights", "King Hammurabi carved 282 laws in stone so everyone could see the rules.", ca);
  ev("olmec", -1200, "The Olmec", "Gulf of Mexico", 17.8, -94.8, "power", "The Olmec carved giant stone heads, and people in the region were already drinking cacao.", ca);
  ev("chinesescript", -1250, "Chinese writing", "Anyang, China", 36.1, 114.3, "ideas", "Priests carved questions to the ancestors on bones. Those symbols grew into Chinese characters.", ca);
  ev("alphabet", -1050, "The alphabet", "Phoenicia (Lebanon)", 34.1, 35.6, "ideas", "Phoenician traders used about 22 letters for sounds, far easier to learn than hundreds of symbols.", ca);
  ev("bantu", -1000, "Bantu peoples spread", "West-Central Africa", 5, 11, "people", "Farmers speaking Bantu languages began moving south and east across Africa over many centuries.", ca);
  ev("olympics", -776, "First Olympic Games", "Olympia, Greece", 37.6, 21.6, "ideas", "Greek city-states that often fought each other paused to compete in races.");
  ev("coins", -600, "The first coins", "Lydia (Turkey)", 38.5, 28, "trade", "Lydia stamped lumps of precious metal so everyone could trust how much they were worth.", ca);
  ev("tomato", -500, "Tomatoes are grown", "Mexico", 19.5, -96.5, "food", "Farmers in Mexico grew tomatoes from small wild berries that first grew in South America.", { ca: true, when: "by 500 BCE" });
  ev("democracy", -508, "Democracy in Athens", "Athens, Greece", 38, 23.7, "rights", "Male citizens of Athens began voting on laws themselves. Women and enslaved people could not vote.");
  ev("buddha", -500, "The Buddha teaches", "Bodh Gaya, India", 24.7, 85, "ideas", "Siddhartha Gautama taught a way to end suffering through kindness and a calm mind.", ca);
  ev("confucius", -500, "Confucius teaches", "Qufu, China", 35.6, 117, "ideas", "Confucius taught respect, learning and fair government, ideas that shaped China for 2,000 years.", ca);
  ev("nok", -500, "Iron in West Africa", "Nok, Nigeria", 9.5, 8, "science", "The Nok people smelted iron and made clay sculptures.", ca);
  ev("alexander", -330, "Alexander's empire", "Greece to India", 32.5, 55, "power", "Alexander the Great conquered from Greece to India, mixing Greek and Asian ideas.", ca);
  ev("library", -285, "Library of Alexandria", "Alexandria, Egypt", 31.2, 29.9, "ideas", "Scholars tried to collect every book in the known world in one place.", ca);
  ev("ashoka", -260, "Ashoka turns to peace", "Pataliputra, India", 25.6, 85.1, "ideas", "After a bloody war, Emperor Ashoka became Buddhist and sent teachers far across Asia.", ca);
  ev("qin", -221, "China is united", "Xianyang, China", 34.3, 108.7, "power", "The first emperor, Qin Shi Huang, united China and made one kind of writing, money and measure.");
  ev("silkroad", -130, "The Silk Road opens", "Chang'an, China", 34.3, 108.9, "trade", "China sent the explorer Zhang Qian west. Soon silk, horses and ideas moved across Asia.", ca);
  ev("monsoon", 50, "Monsoon sea trade", "Arabian Sea", 14, 64, "trade", "Sailors learned the winds blow one way in summer and back in winter, linking Rome, Arabia, India and Africa.", ca);
  ev("jesus", 30, "Christianity begins", "Jerusalem", 31.8, 35.2, "ideas", "Followers of Jesus of Nazareth began spreading his teachings around the Roman world.", ca);
  ev("rome", -27, "The Roman Empire", "Rome", 41.9, 12.5, "power", "Augustus became the first Roman emperor. Rome would rule the Mediterranean for centuries.");
  ev("paper", 105, "Paper is improved", "Luoyang, China", 34.6, 112.4, "science", "Cai Lun made cheap, strong paper from bark, rags and fishing nets.");
  ev("teotihuacan", 100, "Teotihuacan", "Valley of Mexico", 19.7, -98.8, "power", "One of the biggest cities in the world rose around the huge Pyramid of the Sun.", ca);
  ev("maya", 250, "Maya kingdoms", "Tikal, Guatemala", 17.2, -89.6, "science", "Maya astronomers tracked the planets and used a symbol for zero in their calendars.", ca);
  ev("camel", 300, "Camels cross the Sahara", "Sahara Desert", 23, 2, "trade", "Camels can walk for days without water, so the desert became a highway for traders.", ca);
  ev("christianrome", 380, "Rome becomes Christian", "Constantinople", 41, 29, "ideas", "Christianity became the official religion of the Roman Empire.");
  ev("romefalls", 476, "Western Rome falls", "Ravenna, Italy", 44.4, 12.2, "power", "The last emperor in the West was removed. Europe broke into many kingdoms.");
  ev("justinian", 541, "Plague of Justinian", "Constantinople", 40.6, 28.5, "health", "A deadly plague spread along trade routes into the eastern Roman Empire.");
  ev("buddhajapan", 552, "Buddhism reaches Japan", "Nara, Japan", 34.7, 135.8, "ideas", "Monks from Korea brought Buddhist teachings and statues to Japan.", ca);
  ev("islam", 610, "Islam begins", "Mecca, Arabia", 21.4, 39.8, "ideas", "The Prophet Muhammad began sharing the messages that became the Quran.", ca);
  ev("zero", 628, "Zero becomes a number", "Bhinmal, India", 25, 72.3, "science", "The mathematician Brahmagupta wrote rules for adding, taking away and multiplying with zero.");
  ev("tea", 760, "Tea craze in China", "Tang China", 30.3, 120.2, "food", "Lu Yu wrote The Classic of Tea, and tea drinking spread all over China.", ca);
  ev("papersamarkand", 751, "Paper reaches the Islamic world", "Samarkand", 39.65, 66.96, "science", "Around this time, papermaking spread from China into Central Asia and then to Baghdad.", ca);
  ev("baghdad", 830, "House of Wisdom", "Baghdad", 33.3, 44.4, "science", "Scholars translated Greek, Persian and Indian books into Arabic and made new discoveries.", ca);
  ev("algebra", 820, "Algebra", "Baghdad", 33.9, 43.6, "science", "Al-Khwarizmi wrote the book that gave us the word 'algebra'. His name gave us 'algorithm'.", ca);
  ev("gunpowder", 850, "Gunpowder", "Tang China", 34.8, 108, "science", "Chinese alchemists searching for a potion to live forever mixed a powder that exploded.", ca);
  ev("ghanagold", 800, "Empire of gold", "Ghana Empire, West Africa", 15.7, -8, "trade", "The Ghana Empire grew rich trading gold north across the Sahara for salt.", ca);
  ev("swahili", 1000, "Swahili coast cities", "Kilwa, East Africa", -8.9, 39.5, "trade", "Trading towns grew where African, Arab, Persian and Indian merchants met.", ca);
  ev("hawaii", 1000, "Polynesians find Hawaii", "Hawaii", 19.9, -155.6, "people", "Navigators read stars, waves and birds to cross thousands of miles of open ocean.", ca);
  ev("vikings", 1000, "Vikings reach America", "Newfoundland, Canada", 51.6, -55.5, "people", "Norse sailors camped in North America 500 years before Columbus.", ca);
  ev("movabletype", 1040, "Movable type", "Kaifeng, China", 34.8, 114.3, "science", "Bi Sheng made single clay characters that could be rearranged to print any page.", ca);
  ev("cahokia", 1050, "Cahokia", "Mississippi River", 38.66, -90.06, "power", "The largest city north of Mexico had a great earth mound taller than a 10-story building.", ca);
  ev("crusades", 1096, "The Crusades", "Jerusalem", 32.4, 35.9, "power", "European armies marched to fight for Jerusalem, and brought home spices, ideas and trade.");
  ev("compass", 1100, "Compass at sea", "Song China", 25, 118.5, "science", "Chinese sailors used magnetic needles to find north even when clouds hid the stars.", ca);
  ev("angkor", 1150, "Angkor Wat", "Cambodia", 13.41, 103.87, "ideas", "The Khmer built the largest religious building on Earth, first for a Hindu god and later Buddhist.", ca);
  ev("zimbabwe", 1200, "Great Zimbabwe", "Zimbabwe", -20.3, 30.9, "trade", "Stone walls rose around a city that traded gold with the Swahili coast.", ca);
  ev("polysouth", 1200, "Polynesians meet South Americans", "Eastern Polynesia", -9, -139.5, "people", "DNA shows Polynesian and South American people met around 1200, long before Columbus.", ca);
  ev("fibonacci", 1202, "Arabic numerals reach Europe", "Pisa, Italy", 43.7, 10.4, "science", "Fibonacci showed Europe the numbers 0-9, which made math far easier than Roman numerals.");
  ev("genghis", 1206, "The Mongol Empire", "Mongolia", 47.2, 102.8, "power", "Genghis Khan united the Mongols. Their empire became the largest connected land empire ever.");
  ev("magnacarta", 1215, "Magna Carta", "Runnymede, England", 51.4, -0.56, "rights", "English barons forced King John to accept that even a king must follow the law.");
  ev("rockets", 1232, "Fire arrows (rockets)", "Kaifeng, China", 35.2, 113.5, "science", "Chinese defenders launched gunpowder-powered arrows at Mongol attackers.", ca);
  ev("marcopolo", 1271, "Marco Polo travels", "Venice to China", 45.4, 12.3, "trade", "Marco Polo crossed the Mongol Empire to China. His book amazed Europe.");
  ev("papermill", 1276, "Paper mills in Europe", "Fabriano, Italy", 43.34, 12.9, "science", "Italian mills made paper using water power, making it cheap across Europe.", ca);
  ev("aztec", 1325, "Tenochtitlan founded", "Mexico City", 19.43, -99.13, "power", "The Aztecs built a city on a lake, with floating gardens and huge markets.");
  ev("mansamusa", 1324, "Mansa Musa's journey", "Timbuktu, Mali", 16.8, -3, "trade", "Mali's king carried so much gold to Mecca that its price dropped in Cairo.");
  ev("blackdeath", 1347, "The Black Death", "Europe & Asia", 45, 35.4, "health", "A plague spread by fleas on rats killed about a third of Europe's people.");
  ev("catalan", 1375, "Mali on Europe's maps", "Majorca, Spain", 39.6, 2.65, "ideas", "The Catalan Atlas drew Mansa Musa holding gold, and European rulers wanted that gold.");
  ev("renaissance", 1460, "The Renaissance", "Florence, Italy", 43.77, 11.25, "ideas", "Artists and thinkers rediscovered old Greek and Roman ideas and asked new questions.", ca);
  ev("zhenghe", 1405, "Zheng He's treasure fleet", "Nanjing to East Africa", 32, 118.8, "trade", "China sent giant ships as far as East Africa. One brought back a giraffe.");
  ev("portugal", 1415, "Portugal sails south", "Ceuta & Lisbon", 38.7, -9.1, "power", "Portugal began exploring Africa's coast looking for gold and a sea route to Asia.");
  ev("malacca", 1400, "Malacca & Islam in Southeast Asia", "Malacca, Malaysia", 2.2, 102.25, "ideas", "A trading port's rulers became Muslim, and Islam spread across the islands along trade routes.", ca);
  ev("inca", 1438, "The Inca Empire", "Cusco, Peru", -13.5, -72, "power", "The Inca built 40,000 km of roads through the mountains, without the wheel or horses.");
  ev("hangul", 1443, "The Korean alphabet", "Seoul, Korea", 37.57, 126.98, "ideas", "King Sejong made an easy alphabet so ordinary people could read, not just scholars.");
  ev("coffee", 1450, "Coffee is brewed", "Yemen", 13.3, 43.25, "food", "Sufis in Yemen drank coffee to stay awake for night prayers.", ca);
  ev("gutenberg", 1450, "Printing press", "Mainz, Germany", 50, 8.27, "science", "Gutenberg's press could print pages hundreds of times faster than copying by hand.", ca);
  ev("constantinople", 1453, "Constantinople falls", "Istanbul", 41, 29, "power", "Ottoman cannons broke the city's walls. Greek scholars fled west carrying old books.");
  ev("columbus", 1492, "Columbus reaches the Americas", "Caribbean", 24, -74.5, "power", "Trying to reach Asia, Columbus landed in the Caribbean and joined two halves of the world.");
  ev("dagama", 1498, "Sea route to India", "Calicut, India", 11.25, 75.8, "trade", "Vasco da Gama sailed around Africa to India, a new sea road for spices.");
  ev("exchange", 1500, "The Columbian Exchange", "Across the Atlantic", 30, -40, "food", "Plants, animals and germs crossed the ocean both ways and changed every continent's food.", ca);
  ev("luther", 1517, "The Reformation", "Wittenberg, Germany", 51.87, 12.65, "ideas", "Martin Luther challenged the Church. Printed copies of his ideas spread in weeks.");
  ev("smallpox", 1520, "Smallpox in the Americas", "Mexico", 21, -101, "health", "European germs killed millions of Native Americans who had never met these diseases.");
  ev("aztecfall", 1521, "The Aztec capital falls", "Tenochtitlan", 19.0, -98.2, "power", "Spanish soldiers and their many Native allies captured a city already weakened by smallpox.");
  ev("magellan", 1522, "Sailing around the world", "Seville, Spain", 37.4, -6, "trade", "Magellan's crew finished the first trip around the planet (Magellan died on the way).");
  ev("slavetrade", 1526, "Atlantic slave trade grows", "West Africa", 5.1, -1.35, "rights", "Ships began carrying enslaved Africans straight to the Americas. Over 12 million were taken.", ca);
  ev("incafall", 1532, "Spain conquers the Inca", "Cajamarca, Peru", -7.16, -78.5, "power", "A small Spanish force captured the Inca emperor during a civil war worsened by smallpox.");
  ev("potosi", 1545, "Silver mountain of Potosí", "Bolivia", -19.6, -65.75, "trade", "Spain found a mountain full of silver. Enslaved and forced workers dug it out.");
  ev("chili", 1550, "Chili peppers reach Asia", "Goa, India", 15.5, 73.8, "food", "Portuguese ships carried American chilies to India. Now spicy curries use them everywhere.", ca);
  ev("tomatoitaly", 1548, "Tomatoes arrive in Italy", "Florence, Italy", 44.2, 11.9, "food", "Tomatoes from the Americas reached Italy. At first many people only grew them as decoration.");
  ev("chocolate", 1544, "Chocolate reaches Europe", "Spain", 40.4, -3.7, "food", "Maya nobles visiting Spain brought cacao drinks. Europeans added sugar and loved it.");
  ev("manila", 1571, "Manila galleons", "Manila, Philippines", 14.6, 121, "trade", "Spanish ships carried American silver to Manila for Chinese silk: the first truly global trade.");
  ev("sugar", 1640, "Sugar plantations", "Barbados, Caribbean", 13.1, -59.6, "trade", "Sugar made planters rich, forced by the labor of enslaved Africans.", ca);
  ev("galileo", 1609, "Galileo's telescope", "Padua, Italy", 45.4, 11.9, "science", "Galileo saw moons circling Jupiter, proof that not everything circles Earth.");
  ev("jikji", 1377, "Jikji, oldest metal-type book", "Cheongju, Korea", 36.64, 127.49, "science", "Korean monks printed a book with metal letters 78 years before Gutenberg.");
  ev("japanclosed", 1639, "Japan closes its doors", "Edo (Tokyo)", 35.7, 139.7, "power", "Japan's shoguns banned most foreigners for over 200 years.");
  ev("coffeehouse", 1652, "London coffeehouses", "London", 51.51, -0.09, "ideas", "Coffeehouses became places to read news and argue about science, business and politics.");
  ev("newton", 1687, "Newton's laws", "Cambridge, England", 52.2, 0.12, "science", "Isaac Newton explained gravity and motion with math that works from apples to planets.");
  ev("potatoeurope", 1700, "Potatoes feed Europe", "Northern Europe", 52.5, 13.4, "food", "Potatoes grew well in cold soil, so more people had enough to eat.", ca);
  ev("plainshorses", 1700, "Horse nations of the Plains", "Great Plains", 41, -101, "people", "Comanche, Lakota and other nations became expert riders on horses that came from Spain.", ca);
  ev("enlightenment", 1690, "The Enlightenment", "Europe", 48.9, 5, "ideas", "Thinkers like John Locke argued people have natural rights and rulers need their consent.", ca);
  ev("teabritain", 1720, "Britain falls for tea", "London", 51.3, -1.2, "food", "Tea from China became Britain's favorite drink.", ca);
  ev("sevenyears", 1756, "Seven Years' War", "Quebec & the world", 46.8, -71.2, "power", "Britain and France fought on four continents. Britain won but ended up deep in debt.");
  ev("mills", 1780, "Factories and the Industrial Revolution", "Manchester, England", 53.48, -2.24, "science", "Machines spun cotton thread in huge mills, and work moved from homes to factories.", ca);
  ev("steam", 1776, "Watt's steam engine", "Glasgow, Scotland", 55.86, -4.25, "science", "James Watt made a steam engine efficient enough to power factories, then trains and ships.");
  ev("cook", 1770, "Captain Cook's voyages", "Tahiti & the Pacific", -17.6, -149.4, "power", "James Cook mapped Pacific coasts from Australia to Hawaii.");
  ev("amrev", 1776, "American Revolution", "Philadelphia", 39.95, -75.16, "rights", "Thirteen colonies declared that 'all men are created equal' and broke from Britain.");
  ev("bostontea", 1773, "Boston Tea Party", "Boston", 42.36, -71.06, "rights", "Colonists dumped British tea into the harbor to protest a tax they had no vote on.");
  ev("constitution", 1787, "US Constitution", "Philadelphia", 40.3, -76.5, "rights", "The United States wrote rules limiting government power and later added a Bill of Rights.");
  ev("firstfleet", 1788, "British colony in Australia", "Sydney", -33.86, 151.2, "power", "Britain sent ships of convicts to Australia, with terrible results for Aboriginal peoples.");
  ev("frenchrev", 1789, "French Revolution", "Paris", 48.86, 2.35, "rights", "The people of France overthrew their king and declared the Rights of Man.");
  ev("haiti", 1791, "Haitian Revolution", "Haiti", 18.5, -72.3, "rights", "Enslaved people rose up, beat Napoleon's army and founded the first free Black republic.");
  ev("cottongin", 1793, "The cotton gin", "Georgia, USA", 32.1, -81.1, "science", "Eli Whitney's machine cleaned cotton fast, which made slavery spread even further in the US South.");
  ev("jenner", 1796, "The first vaccine", "Berkeley, England", 51.69, -2.46, "health", "Edward Jenner used mild cowpox to protect people from deadly smallpox.");
  ev("louisiana", 1803, "Louisiana Purchase", "New Orleans", 29.95, -90.07, "power", "Napoleon sold a huge piece of North America to the US, doubling its size.");
  ev("napoleon", 1804, "Napoleon's empire", "Paris", 49.5, 3.5, "power", "Napoleon crowned himself emperor and conquered much of Europe.");
  ev("bolivar", 1810, "Latin America breaks free", "Caracas, Venezuela", 10.5, -66.9, "rights", "With Spain's king taken by Napoleon, Simón Bolívar and others led wars for independence.", ca);
  ev("tambora", 1815, "Tambora erupts", "Indonesia", -8.25, 118, "planet", "The biggest volcanic eruption in modern history threw ash high into the sky around the world.");
  ev("nosummer", 1816, "The Year Without a Summer", "Europe & North America", 44, -30, "planet", "Ash blocked sunlight. It snowed in June, crops failed and horses went hungry.");
  ev("frankenstein", 1818, "Frankenstein is published", "Geneva (written 1816)", 46.2, 6.15, "ideas", "Stuck indoors by stormy weather, Mary Shelley began writing the first science-fiction novel.");
  ev("bicycle", 1817, "The first bicycle", "Mannheim, Germany", 49.5, 8.47, "science", "Karl Drais built a 'running machine'. Some historians think it was a horse-free way to travel.");
  ev("railway", 1825, "Railways", "Stockton, England", 54.57, -1.32, "science", "Steam trains began carrying passengers, making long trips take hours instead of days.");
  ev("darwin", 1835, "Darwin in the Galápagos", "Galápagos Islands", -0.9, -89.6, "science", "Darwin noticed finches differ island to island, the start of his idea of evolution.");
  ev("opium", 1839, "Opium Wars", "Canton, China", 23.1, 113.3, "power", "Britain went to war to keep selling opium in China, and took Hong Kong.");
  ev("lovelace", 1843, "The first computer program", "London", 51.2, 0.5, "science", "Ada Lovelace wrote steps for Babbage's machine and imagined computers making music.");
  ev("famine", 1845, "Irish Potato Famine", "Ireland", 53, -8, "health", "A blight rotted potatoes. About a million people died and a million more left Ireland.");
  ev("thoreau", 1849, "Civil Disobedience", "Concord, USA", 42.46, -71.35, "rights", "Thoreau wrote that people should peacefully refuse to obey unfair laws.");
  ev("irishus", 1850, "Irish move to America", "New York", 40.7, -74, "people", "Millions of Irish families built new lives in American cities.", ca);
  ev("perry", 1853, "US ships open Japan", "Tokyo Bay", 35.3, 139.7, "power", "American warships forced Japan to open its ports to trade.");
  ev("oil", 1859, "The first oil well", "Pennsylvania", 41.6, -79.7, "planet", "Drillers struck oil, which soon lit lamps and later fueled cars and planes.");
  ev("origin", 1859, "On the Origin of Species", "London", 51.7, -0.6, "science", "Darwin's book explained how living things change over many generations.");
  ev("civilwar", 1861, "US Civil War", "South Carolina", 32.75, -79.87, "rights", "The North and South fought over slavery. Four million enslaved people were freed.");
  ev("meiji", 1868, "Japan modernizes", "Tokyo", 36.0, 140.2, "power", "The Meiji leaders built railways, factories and a modern army in just a few decades.");
  ev("suez", 1869, "Suez Canal", "Egypt", 30.6, 32.3, "trade", "A canal joined the Mediterranean to the Red Sea, so ships no longer sailed around Africa.");
  ev("milkchoc", 1875, "Milk chocolate", "Vevey, Switzerland", 46.46, 6.84, "food", "Daniel Peter mixed in dried milk and made the first milk chocolate.");
  ev("edison", 1879, "The light bulb", "New Jersey", 40.56, -74.33, "science", "Edison's lab made a bulb that glowed for hours. Cities began to light up at night.");
  ev("timezones", 1883, "Time zones", "Chicago", 41.88, -87.63, "trade", "Railroads needed shared clocks for timetables, so North America split into time zones.");
  ev("africascramble", 1884, "The Scramble for Africa", "Berlin", 52.5, 13.4, "power", "European powers met in Berlin and divided Africa between them, without asking Africans.");
  ev("car", 1886, "The motor car", "Mannheim, Germany", 49.1, 8.9, "science", "Karl Benz built a car with a gasoline engine.");
  ev("pizza", 1889, "Pizza Margherita", "Naples, Italy", 40.85, 14.27, "food", "Naples bakers topped flatbread with tomato, cheese and basil, and pizza went global.");
  ev("gandhisa", 1893, "Gandhi in South Africa", "Pietermaritzburg", -29.6, 30.38, "rights", "Thrown off a train for being Indian, Gandhi began organizing peaceful protest.");
  ev("adwa", 1896, "Ethiopia wins at Adwa", "Adwa, Ethiopia", 14.16, 38.9, "rights", "Ethiopia defeated an invading Italian army and stayed independent.");
  ev("yellowfever", 1900, "Mosquitoes spread yellow fever", "Havana, Cuba", 23.1, -82.4, "health", "Doctors proved mosquitoes carry yellow fever, so killing mosquitoes could stop it.");
  ev("wright", 1903, "The first airplane flight", "Kitty Hawk, USA", 36.02, -75.67, "science", "The Wright brothers flew for 12 seconds. 66 years later people walked on the Moon.");
  ev("einstein", 1905, "E = mc²", "Bern, Switzerland", 46.95, 7.45, "science", "Einstein showed a tiny bit of matter holds a huge amount of energy.");
  ev("modelt", 1908, "Model T car", "Detroit", 42.33, -83.05, "science", "Ford's assembly line made cars cheap enough for ordinary families.");
  ev("panama", 1914, "Panama Canal", "Panama", 9.08, -79.68, "trade", "A canal cut through Central America joined the Atlantic and Pacific.");
  ev("ww1", 1914, "World War I", "Sarajevo", 43.86, 18.41, "power", "The murder of Archduke Franz Ferdinand pulled Europe's empires into a world war.");
  ev("russianrev", 1917, "Russian Revolution", "St Petersburg", 59.94, 30.3, "power", "Worn out by war, Russians overthrew the Tsar. Communists took power.");
  ev("flu", 1918, "The 1918 flu", "Worldwide", 40, -95, "health", "A flu carried by soldiers and ships infected about a third of the world's people.");
  ev("versailles", 1919, "Treaty of Versailles", "Versailles, France", 48.8, 2.12, "power", "The peace treaty blamed Germany and made it pay, leaving deep anger.");
  ev("goddard", 1926, "The liquid-fuel rocket", "Massachusetts", 42.2, -71.8, "science", "Robert Goddard launched the first liquid-fuel rocket. It flew 2.5 seconds.");
  ev("penicillin", 1928, "Penicillin", "London", 51.5, -0.17, "health", "Alexander Fleming noticed mold killing bacteria: the first antibiotic.");
  ev("depression", 1929, "The Great Depression", "New York", 40.9, -73, "trade", "The stock market crashed and millions around the world lost their jobs.");
  ev("saltmarch", 1930, "The Salt March", "Dandi, India", 20.9, 72.8, "rights", "Gandhi walked 390 km to the sea to make salt, peacefully breaking an unfair British law.");
  ev("nazis", 1933, "The Nazis take power", "Berlin", 52.8, 13.9, "power", "Hitler rose to power in Germany, promising to undo the treaty and blaming Jewish people.");
  ev("ww2", 1939, "World War II", "Poland & the world", 52.2, 21, "power", "Germany invaded Poland. The war would kill over 60 million people.");
  ev("holocaust", 1941, "The Holocaust", "Auschwitz, Poland", 50.03, 19.2, "rights", "The Nazis murdered six million Jewish people and millions of others.");
  ev("pearlharbor", 1941, "Pearl Harbor", "Hawaii", 21.35, -157.95, "power", "Japan attacked the US fleet in Hawaii, and the United States joined the war.");
  ev("turing", 1941, "Codebreakers and computers", "Bletchley Park, England", 51.99, -0.74, "science", "Alan Turing and others built machines to crack secret codes, early steps to computers.", ca);
  ev("v2", 1944, "V-2 rockets", "Peenemünde, Germany", 54.14, 13.77, "science", "Germany built the first rocket to reach space, as a weapon.");
  ev("hiroshima", 1945, "The atomic bomb", "Hiroshima, Japan", 34.4, 132.45, "power", "The US dropped atomic bombs on Hiroshima and Nagasaki, and the war ended.");
  ev("un", 1945, "The United Nations", "San Francisco", 37.77, -122.4, "rights", "Countries formed the UN to talk through problems instead of fighting.");
  ev("india", 1947, "India's independence", "Delhi", 28.6, 77.2, "rights", "India won freedom from Britain. The land was split into India and Pakistan.");
  ev("transistor", 1947, "The transistor", "New Jersey", 40.68, -74.4, "science", "A tiny electric switch replaced glowing tubes. Every phone now has billions.");
  ev("udhr", 1948, "Human rights for everyone", "Paris", 48.9, 2.9, "rights", "The UN listed rights every person has, no matter where they were born.");
  ev("who", 1948, "World Health Organization", "Geneva", 46.23, 6.13, "health", "Countries teamed up to fight disease together.");
  ev("prc", 1949, "People's Republic of China", "Beijing", 39.9, 116.4, "power", "After a long civil war, the Communist Party took control of China.");
  ev("dna", 1953, "DNA's double helix", "Cambridge, England", 52.6, 0.4, "science", "Rosalind Franklin's X-ray photo helped Watson and Crick see DNA's twisted-ladder shape.");
  ev("montgomery", 1955, "Montgomery Bus Boycott", "Alabama", 32.37, -86.3, "rights", "Rosa Parks refused to give up her seat, and Martin Luther King Jr. led a peaceful boycott.");
  ev("ghana", 1957, "Ghana's independence", "Accra, Ghana", 5.6, -0.19, "rights", "Ghana became the first African colony south of the Sahara to win independence. 17 more followed in 1960.");
  ev("sputnik", 1957, "Sputnik", "Baikonur, Kazakhstan", 45.9, 63.3, "science", "The Soviet Union launched the first satellite. Americans raced to catch up.");
  ev("keeling", 1958, "Measuring carbon dioxide", "Mauna Loa, Hawaii", 19.5, -155.6, "planet", "Charles Keeling began measuring CO₂ in the air. The line has gone up every year since.");
  ev("arpa", 1958, "ARPA is created", "Washington, DC", 38.9, -77, "science", "Shocked by Sputnik, the US funded a research agency that later built the internet's ancestor.");
  ev("microchip", 1958, "The microchip", "Dallas, USA", 32.8, -96.8, "science", "Jack Kilby put many transistors on one chip.");
  ev("greenrev", 1965, "The Green Revolution", "Punjab, India", 30.9, 75.85, "food", "New wheat and rice varieties helped India grow enough food to feed itself.", ca);
  ev("earthrise", 1968, "Earthrise photo", "Orbiting the Moon", 10, -170, "planet", "Apollo 8 astronauts photographed Earth rising over the Moon, small, blue and alone.");
  ev("apollo", 1969, "People walk on the Moon", "Cape Canaveral, USA", 28.5, -80.6, "science", "Neil Armstrong and Buzz Aldrin landed on the Moon.");
  ev("arpanet", 1969, "ARPANET", "Los Angeles", 34.07, -118.44, "science", "Two computers 500 km apart sent the first message of the internet's ancestor: 'lo'.");
  ev("earthday", 1970, "The first Earth Day", "USA", 39.5, -98, "planet", "Twenty million Americans rallied to protect the environment.");
  ev("pc", 1977, "Home computers", "California", 36.5, -121.5, "science", "Apple, Commodore and others sold computers ordinary families could use.");
  ev("smallpoxgone", 1980, "Smallpox is wiped out", "Worldwide (WHO)", 0, 20, "health", "After a worldwide vaccine campaign, the first human disease was eliminated.");
  ev("www", 1989, "The World Wide Web", "CERN, Geneva", 46.5, 5.6, "science", "Tim Berners-Lee invented web pages and links, and gave the idea away for free.");
  ev("berlinwall", 1989, "The Berlin Wall falls", "Berlin", 52.2, 12.8, "rights", "Crowds tore down the wall splitting Germany. Two years later the Soviet Union ended.");
  ev("mandela", 1994, "Mandela is elected", "Pretoria, South Africa", -25.7, 28.2, "rights", "After 27 years in prison, Nelson Mandela became president and apartheid ended.");
  ev("smartphone", 2007, "The smartphone", "Cupertino, California", 37.33, -122.03, "science", "Phones became pocket computers with the internet always on.");
  ev("arabspring", 2011, "The Arab Spring", "Tunis, Tunisia", 36.8, 10.18, "rights", "Protesters shared videos on phones, and uprisings spread across North Africa and the Middle East.");
  ev("paris", 2015, "Paris climate agreement", "Paris", 48.4, 1.6, "planet", "Nearly every country agreed to cut the gases that warm the planet.");
  ev("covid", 2020, "COVID-19 pandemic", "Worldwide", 30.6, 114.3, "health", "A new coronavirus spread to every continent and closed schools around the world.");
  ev("mrna", 2020, "mRNA vaccines", "Worldwide labs", 50, 8.6, "health", "Scientists built new vaccines in under a year using decades of DNA research.");

  // ---------- Threads: cause -> effect ----------
  ln("farming", "cities", "Extra food meant not everyone had to farm, so towns could grow.");
  ln("rice", "greenrev", "New high-yield rice built on 9,000 years of rice farming.");
  ln("cities", "writing", "Busy cities needed a way to track grain, taxes and trades.");
  ln("wheel", "horse", "Wheeled carts and chariots made tamed horses even more useful.");
  ln("writing", "hammurabi", "With writing, laws could be carved and shown to everyone.");
  ln("writing", "alphabet", "Egyptian signs inspired simpler letters that stood for sounds.");
  ln("alphabet", "library", "Easy letters meant more books, and Alexandria tried to collect them all.");
  ln("chinesescript", "qin", "The first emperor made one standard script for all of China.");
  ln("chinesescript", "hangul", "Chinese characters were so hard to learn that King Sejong created a simpler alphabet.");
  ln("horse", "silkroad", "China needed horses and allies against nomad riders, so it sent envoys west.");
  ln("horse", "genghis", "Mongol riders could travel 100 km a day, which built an empire.");
  ln("coins", "silkroad", "Coins made trade with strangers far easier.");
  ln("bantu", "swahili", "Swahili is a Bantu language; the coast towns grew from Bantu farming communities.");
  ln("bantu", "zimbabwe", "Bantu-speaking Shona ancestors built Great Zimbabwe.");
  ln("democracy", "enlightenment", "Enlightenment thinkers studied Athens when arguing that people should rule themselves.");
  ln("buddha", "ashoka", "Ashoka followed the Buddha's teachings after his war.");
  ln("ashoka", "silkroad", "Ashoka's missionaries sent Buddhism along routes that became the Silk Road.");
  ln("silkroad", "buddhajapan", "Buddhism travelled the Silk Road to China and Korea, then to Japan.");
  ln("buddha", "angkor", "Indian religions spread to Southeast Asia and shaped Angkor.");
  ln("confucius", "hangul", "King Sejong ruled by Confucian ideals of caring for ordinary people.");
  ln("alexander", "library", "Alexander founded Alexandria, and his general's family built its library.");
  ln("alexander", "silkroad", "Greek kingdoms left in Central Asia became stops on the Silk Road.");
  ln("library", "baghdad", "Greek books preserved in places like Alexandria were translated in Baghdad.");
  ln("qin", "silkroad", "A united China had the power to send explorers and armies west.");
  ln("silkroad", "justinian", "Plague travelled along the same routes as silk and spices.");
  ln("rome", "jesus", "Roman roads and a shared language helped Christianity spread fast.");
  ln("jesus", "christianrome", "Christianity grew until Rome's emperors adopted it.");
  ln("rome", "romefalls", "The empire grew too big and costly to defend.");
  ln("monsoon", "swahili", "Monsoon winds brought Arab, Persian and Indian traders to East Africa.");
  ln("monsoon", "angkor", "Indian traders and priests sailed to Southeast Asia on the monsoon winds.");
  ln("monsoon", "malacca", "Malacca sat where monsoon routes met, so traders waited there for the wind to change.");
  ln("islam", "baghdad", "The Islamic caliphs built Baghdad and paid scholars to gather knowledge.");
  ln("islam", "malacca", "Muslim merchants carried Islam across the Indian Ocean.");
  ln("islam", "crusades", "Christian and Muslim rulers fought over holy land in Jerusalem.");
  ln("christianrome", "crusades", "The Pope called on Christian knights to march east.");
  ln("paper", "papersamarkand", "Papermaking spread west from China along the Silk Road.");
  ln("papersamarkand", "baghdad", "Cheap paper let Baghdad's scholars copy thousands of books.");
  ln("papersamarkand", "papermill", "Papermaking moved from the Islamic world through Spain into Italy.");
  ln("paper", "movabletype", "Printing needs lots of cheap paper.");
  ln("zero", "algebra", "Al-Khwarizmi learned Indian numbers, with zero, and built on them.");
  ln("maya", "chocolate", "Maya nobles brought cacao to Spain, a drink their people had enjoyed for centuries.");
  ln("olmec", "maya", "Olmec calendars, writing and cacao drinks passed down to the Maya.");
  ln("algebra", "fibonacci", "Fibonacci learned Arabic mathematics from traders in North Africa.");
  ln("baghdad", "renaissance", "Arabic translations of Greek science reached Europe and sparked new learning.");
  ln("gunpowder", "rockets", "The same explosive powder could push arrows through the air.");
  ln("gunpowder", "constantinople", "Gunpowder spread west, and Ottoman cannons broke the ancient walls.");
  ln("camel", "ghanagold", "Camel caravans carried Ghana's gold across the Sahara.");
  ln("ghanagold", "mansamusa", "Mali took over the gold trade that Ghana built.");
  ln("mansamusa", "catalan", "Stories of Musa's gold reached Europe and went onto maps.");
  ln("catalan", "portugal", "Portugal wanted to reach Africa's gold by sea.");
  ln("swahili", "zimbabwe", "Swahili traders bought Great Zimbabwe's gold and shipped it overseas.");
  ln("swahili", "zhenghe", "Zheng He's fleet sailed to the Swahili coast, and a giraffe went to China.");
  ln("compass", "zhenghe", "Compasses helped the treasure fleet cross open ocean.");
  ln("compass", "portugal", "The compass reached Europe and let sailors head into open ocean.");
  ln("movabletype", "jikji", "Printing ideas from China spread to Korea, which switched to metal letters.");
  ln("papermill", "gutenberg", "Gutenberg needed Europe's cheap paper to print thousands of pages.");
  ln("genghis", "marcopolo", "Mongol rule made the whole Silk Road safe enough to cross.");
  ln("genghis", "blackdeath", "Busy Mongol trade routes carried plague from Asia to Europe.");
  ln("genghis", "rockets", "Chinese defenders fired rockets at the Mongols, and the Mongols spread the idea.");
  ln("marcopolo", "columbus", "Columbus owned Marco Polo's book and made notes in it about Asia's riches.");
  ln("blackdeath", "renaissance", "With so many dead, surviving workers earned more, and old ways of thinking were shaken.");
  ln("crusades", "renaissance", "Contact with the Muslim world brought new goods and ideas back to Italy.");
  ln("magnacarta", "constitution", "The idea that rulers obey the law carried into American founding documents.");
  ln("magnacarta", "enlightenment", "Magna Carta became a famous example of limits on a king.");
  ln("fibonacci", "galileo", "Easy numbers made the maths of modern science possible.");
  ln("constantinople", "renaissance", "Greek scholars fled to Italy carrying ancient books.");
  ln("constantinople", "columbus", "The Ottomans controlled the land roads to Asia, one reason Europeans looked for sea routes.");
  ln("portugal", "dagama", "Decades of Portuguese voyages down Africa's coast led to India.");
  ln("portugal", "slavetrade", "Portuguese traders began the Atlantic slave trade.");
  ln("renaissance", "galileo", "Renaissance curiosity led people to test ideas with experiments.");
  ln("gutenberg", "luther", "Printed pamphlets spread Luther's ideas across Europe in weeks.");
  ln("gutenberg", "galileo", "Printed books let scientists share discoveries quickly.");
  ln("aztec", "aztecfall", "Tenochtitlan's enemies joined the Spanish to overthrow the Aztecs.");
  ln("columbus", "exchange", "Once ships crossed regularly, everything living crossed too.");
  ln("columbus", "smallpox", "Sailors carried germs Native Americans had never faced.");
  ln("smallpox", "aztecfall", "Smallpox killed much of Tenochtitlan during the siege.");
  ln("smallpox", "incafall", "Smallpox killed the Inca emperor and started a civil war.");
  ln("inca", "incafall", "The Inca Empire was split by a civil war over who should rule.");
  ln("smallpox", "slavetrade", "With so many Native Americans dead, colonists turned to enslaved Africans.");
  ln("smallpox", "jenner", "Smallpox was so deadly that finding a way to stop it became urgent.");
  ln("incafall", "potosi", "Conquering the Inca gave Spain control of the Andes and its silver.");
  ln("potosi", "manila", "American silver paid for Chinese silk and porcelain.");
  ln("magellan", "manila", "Magellan's voyage showed Spain the Pacific route to the Philippines.");
  ln("dagama", "chili", "Portuguese ships carried American chilies to India.");
  ln("dagama", "magellan", "Portugal's success pushed Spain to find its own route to Asia.");
  ln("exchange", "chili", "Chili peppers were one of the Americas' gifts to the world.");
  ln("exchange", "potatoeurope", "Andean potatoes crossed the ocean to Europe.");
  ln("potato", "exchange", "Potatoes were one of the most important crops to cross the ocean.");
  ln("maize", "exchange", "Corn crossed to Africa, Europe and Asia, and is now grown on every farmed continent.");
  ln("tomato", "tomatoitaly", "Spanish ships brought tomatoes from Mexico to Europe.");
  ln("exchange", "plainshorses", "Spanish horses spread north and changed life on the Great Plains.");
  ln("exchange", "sugar", "Sugar cane was planted in the Americas on huge plantations.");
  ln("slavetrade", "sugar", "Plantations were worked by enslaved Africans.");
  ln("tomatoitaly", "pizza", "Once Italians started eating tomatoes, Naples put them on flatbread.");
  ln("chocolate", "milkchoc", "Europeans kept experimenting with chocolate for 300 years.");
  ln("galileo", "newton", "Newton built on Galileo's experiments with motion.");
  ln("newton", "enlightenment", "If nature followed rules, thinkers asked if society could too.");
  ln("newton", "steam", "Newton's science encouraged engineers to measure and improve machines.");
  ln("newton", "apollo", "NASA calculated the path to the Moon with Newton's laws.");
  ln("coffee", "coffeehouse", "Coffee spread from Yemen through the Ottoman Empire to London.");
  ln("coffeehouse", "enlightenment", "Coffeehouses were where people read, debated and shared new ideas.");
  ln("luther", "enlightenment", "Questioning the Church opened the door to questioning kings.");
  ln("tea", "teabritain", "Ships brought Chinese tea to Britain.");
  ln("teabritain", "bostontea", "Britain taxed tea in its colonies.");
  ln("teabritain", "opium", "Britain paid for so much tea that it sold opium to China to get its silver back.");
  ln("sevenyears", "bostontea", "Britain taxed its colonies to pay its war debts.");
  ln("sevenyears", "amrev", "With France beaten, colonists felt less need for British protection.");
  ln("bostontea", "amrev", "Britain punished Boston, and the colonies united against it.");
  ln("enlightenment", "amrev", "The Declaration borrowed Locke's ideas about rights.");
  ln("amrev", "constitution", "The new country needed a government.");
  ln("amrev", "frenchrev", "France helped the Americans, went broke, and heard their ideas about liberty.");
  ln("amrev", "firstfleet", "Britain could no longer send convicts to America, so it sent them to Australia.");
  ln("cook", "firstfleet", "Cook's voyage mapped the coast where Britain later settled.");
  ln("australia", "firstfleet", "British settlers took land Aboriginal peoples had lived on for tens of thousands of years.");
  ln("enlightenment", "frenchrev", "French thinkers said power should come from the people.");
  ln("frenchrev", "haiti", "The French 'Rights of Man' inspired enslaved people in France's richest colony.");
  ln("sugar", "haiti", "Haiti's sugar plantations were among the cruelest in the world.");
  ln("frenchrev", "napoleon", "Chaos after the revolution let a general take over.");
  ln("haiti", "louisiana", "After losing Haiti, Napoleon gave up on America and sold Louisiana.");
  ln("napoleon", "bolivar", "Napoleon took Spain's king, so Spain's colonies began ruling themselves.");
  ln("steam", "mills", "Steam power let factories be built anywhere, not just by rivers.");
  ln("steam", "railway", "Put a steam engine on wheels and you have a train.");
  ln("mills", "cottongin", "British mills wanted endless cotton.");
  ln("cottongin", "civilwar", "Cotton made slavery hugely profitable, deepening the split between North and South.");
  ln("slavetrade", "civilwar", "Slavery in America began with the Atlantic slave trade.");
  ln("mills", "keeling", "Burning coal for factories started raising carbon dioxide in the air.");
  ln("potatoeurope", "mills", "More food meant more people, and many of them moved to factory towns.");
  ln("potatoeurope", "famine", "Poor Irish families depended on one crop, so when it failed there was nothing else.");
  ln("famine", "irishus", "Starving families left for America.");
  ln("tambora", "nosummer", "Ash in the sky cooled the whole planet.");
  ln("nosummer", "frankenstein", "A cold, stormy summer kept Mary Shelley's friends indoors telling ghost stories.");
  ln("nosummer", "bicycle", "Crops failed and horses starved; some historians link this to Drais's horse-free machine.");
  ln("railway", "timezones", "Trains needed everyone's clocks to agree.");
  ln("railway", "meiji", "Japan built railways to catch up with Western powers.");
  ln("darwin", "origin", "Darwin spent 20 years turning his island notes into a theory.");
  ln("origin", "dna", "Scientists hunted for how traits pass from parents to children.");
  ln("opium", "perry", "Japan saw China beaten and knew it could not fight the Western ships.");
  ln("perry", "meiji", "Forced open, Japan decided to modernize fast.");
  ln("japanclosed", "perry", "After 200 closed years, Japan was far behind in weapons.");
  ln("meiji", "pearlharbor", "Japan built a powerful empire that later clashed with the US in the Pacific.");
  ln("thoreau", "gandhisa", "Gandhi read Thoreau's essay and used its ideas.");
  ln("gandhisa", "saltmarch", "Gandhi brought his peaceful-protest methods home to India.");
  ln("saltmarch", "india", "Peaceful protest helped force Britain to leave.");
  ln("saltmarch", "montgomery", "Martin Luther King Jr. studied Gandhi's methods.");
  ln("gandhisa", "mandela", "The protest movement Gandhi began in South Africa inspired later fights against apartheid.");
  ln("steam", "suez", "Steamships could use a canal that sailing ships struggled with.");
  ln("suez", "africascramble", "Britain took control of Egypt to protect the canal.");
  ln("suez", "panama", "Suez's builder, de Lesseps, tried to build a canal in Panama next.");
  ln("yellowfever", "panama", "Killing mosquitoes finally let workers survive long enough to finish the canal.");
  ln("africascramble", "adwa", "Italy invaded Ethiopia to grab its share of Africa.");
  ln("africascramble", "ghana", "Africans organized to win back the right to govern themselves.");
  ln("adwa", "ghana", "Ethiopia's victory became a symbol of African freedom.");
  ln("oil", "car", "Gasoline from oil made small, powerful engines possible.");
  ln("car", "modelt", "Ford made Benz's invention cheap.");
  ln("oil", "keeling", "Burning oil added even more carbon dioxide.");
  ln("edison", "transistor", "Electric power grew into the electronics industry.");
  ln("wright", "apollo", "Airplanes grew the aerospace industry that went on to build spacecraft.");
  ln("einstein", "hiroshima", "E = mc² showed the huge energy that atom bombs release.");
  ln("irishus", "civilwar", "About 150,000 Irish immigrants fought for the Union.");
  ln("ww1", "russianrev", "The war left Russia starving and angry.");
  ln("ww1", "flu", "Crowded troop camps and ships spread the flu around the world.");
  ln("ww1", "versailles", "The winners wrote the peace terms.");
  ln("versailles", "nazis", "Hitler used anger over the treaty to win support.");
  ln("depression", "nazis", "Desperate, jobless Germans turned to extreme leaders.");
  ln("nazis", "ww2", "Hitler invaded Germany's neighbors.");
  ln("nazis", "holocaust", "Nazi hatred became mass murder.");
  ln("ww2", "hiroshima", "The US used the bomb to force Japan to surrender.");
  ln("pearlharbor", "hiroshima", "The attack brought the US into the war against Japan.");
  ln("ww2", "un", "After two world wars, countries wanted a way to keep peace.");
  ln("ww2", "india", "The war left Britain too weak to hold its empire.");
  ln("ww2", "turing", "Winning the war depended on reading enemy codes.");
  ln("holocaust", "udhr", "The world promised 'never again' and wrote down everyone's rights.");
  ln("un", "udhr", "The UN wrote the Universal Declaration of Human Rights.");
  ln("un", "who", "The UN created a health agency for the whole world.");
  ln("flu", "who", "The 1918 flu showed diseases need a worldwide response.");
  ln("jenner", "smallpoxgone", "Jenner's vaccine idea was used to wipe out smallpox.");
  ln("who", "smallpoxgone", "The WHO led the campaign to vaccinate the world.");
  ln("goddard", "v2", "German rocket engineers followed liquid-fuel work like Goddard's.");
  ln("rockets", "goddard", "Rockets had been around since China's fire arrows; Goddard made them fly with liquid fuel.");
  ln("v2", "sputnik", "Soviet engineers learned from captured V-2 rockets.");
  ln("v2", "apollo", "Wernher von Braun, who led the V-2, designed the rocket that flew to the Moon.");
  ln("ww2", "prc", "Japan's invasion weakened China's government and helped the Communists win.");
  ln("sputnik", "arpa", "The US created ARPA so it would never be surprised again.");
  ln("sputnik", "apollo", "The space race began, and the US aimed for the Moon.");
  ln("arpa", "arpanet", "ARPA funded the network that became the internet.");
  ln("lovelace", "turing", "Turing studied Babbage and Lovelace's idea of a machine that follows instructions.");
  ln("turing", "transistor", "Early computers showed the need for faster, smaller switches.");
  ln("transistor", "microchip", "Engineers packed transistors onto one chip.");
  ln("microchip", "apollo", "Apollo's guidance computer used early microchips.");
  ln("microchip", "pc", "Cheap chips made home computers possible.");
  ln("arpanet", "www", "The web was built on top of the internet.");
  ln("www", "smartphone", "Phones were built to carry the web in your pocket.");
  ln("smartphone", "arabspring", "Protesters used phones and social media to organize and show the world.");
  ln("sputnik", "earthrise", "The space race sent Apollo 8 around the Moon.");
  ln("earthrise", "apollo", "Apollo 8 tested the trip around the Moon seven months before the landing.");
  ln("earthrise", "earthday", "The photo made people feel how fragile the planet is.");
  ln("earthday", "paris", "The environmental movement grew into global climate agreements.");
  ln("keeling", "paris", "Rising CO₂ measurements proved the planet was warming.");
  ln("dna", "mrna", "Understanding genetic code made mRNA vaccines possible.");
  ln("covid", "mrna", "The pandemic drove scientists to finish mRNA vaccines fast.");
  ln("jenner", "mrna", "Every vaccine builds on Jenner's idea: train the body before the disease arrives.");
  ln("penicillin", "ww2", "Mass-produced penicillin saved thousands of wounded soldiers.");
  ln("ww2", "berlinwall", "After the war, Germany was split between the Soviet side and the West.");
  ln("russianrev", "berlinwall", "The Soviet Union built by the revolution later ruled East Germany.");
  ln("udhr", "mandela", "The world's human-rights promises put pressure on apartheid South Africa.");
  ln("montgomery", "mandela", "The US civil-rights movement inspired protest and support worldwide.");
  ln("sugar", "milkchoc", "Cheap sugar made sweet chocolate bars possible.");
  ln("india", "greenrev", "Newly independent India needed to feed its fast-growing population.");
  ln("hawaii", "cook", "The Tahitian navigator Tupaia sailed with Cook and drew him a map of Pacific islands.");

  window.EVENTS = EVENTS;
  window.LINKS = LINKS;
  window.KINDS = {
    food: "Food & farming", trade: "Trade & travel", ideas: "Ideas & beliefs", science: "Inventions & science",
    power: "Empires & wars", rights: "Freedom & rights", health: "Health & disease", planet: "Planet & climate", people: "People on the move"
  };
})();
