// Generated by tools/build_images_js.py. Pictures from Wikimedia Commons, free licenses only.
window.IMAGES = {
"australia": {
"artist": "Dietmar Rabich",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Kakadu_(AU),_Kakadu_National_Park,_Ubirr_Rock_Art_--_2019_--_4171.jpg"
},
"farming": {
"artist": "Bjoertvedt, Lars A\n\ntranslator: Manlleus (ca)",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Fertile_crescent_Neolithic_B_circa_7500_BC.svg"
},
"rice": {
"artist": "China News Service",
"license": "CC BY 3.0",
"source": "https://commons.wikimedia.org/wiki/File:20201102.Hengnan.Hybrid_rice_Sanyou-1.6.jpg"
},
"maize": {
"artist": "Franz Eugen Köhler, Köhler's Medizinal-Pflanzen",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Zea_mays_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-283.jpg"
},
"potato": {
"artist": "Scott Bauer, USDA ARS",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Patates.jpg"
},
"cities": {
"artist": "Osama Shukir Muhammed Amin FRCP(Glasg)",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Warka_vase_(background_retouched).jpg"
},
"wheel": {
"artist": "Bybbisch94, Christian Gebhardt",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Landesmuseum_W%C3%BCrttemberg_Kelten_011.4.jpg"
},
"writing": {
"artist": "Bjørn Christian Tørrissen",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Xerxes_Cuneiform_Van.JPG"
},
"caral": {
"artist": "Jon Gudorf Photography",
"license": "CC BY-SA 2.0",
"source": "https://commons.wikimedia.org/wiki/File:Mayor_Pyramid_and_circular_enclosure._Caral,_Peru.jpg"
},
"indus": {
"artist": "Saqib Qayyum",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Mohenjodaro_-_view_of_the_stupa_mound.JPG"
},
"pyramid": {
"artist": "Douwe C. van der Zee",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Great_Pyramid_of_Giza_-_Pyramid_of_Khufu.jpg"
},
"horse": {
"artist": "PtrQs",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:20150429_Schoeningen_PrzewalskiPferd_DSC05760_PtrQs.jpg"
},
"hammurabi": {
"artist": "Mbzt",
"license": "CC BY 3.0",
"source": "https://commons.wikimedia.org/wiki/File:P1050763_Louvre_code_Hammurabi_face_rwk.JPG"
},
"olmec": {
"artist": "Marshall Astor (Life on the Edge)",
"license": "CC BY-SA 2.0",
"source": "https://commons.wikimedia.org/wiki/File:San_Lorenzo_Monument_4_crop.jpg"
},
"chinesescript": {
"artist": "",
"license": "CC0",
"source": "https://commons.wikimedia.org/wiki/File:Shang_Inscribed_Ox_Scapula_(for_divination).jpg"
},
"alphabet": {
"artist": "Onceinawhile",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:National_Museum_of_Beirut_%E2%80%93_Ahiram_sarcophagus_inscription_1.jpg"
},
"bantu": {
"artist": "",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:East_and_southern_africa_early_iron_age.png"
},
"olympics": {
"artist": "Bgabel",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:GR-olympia-palaestra.jpg"
},
"coins": {
"artist": "brewbooks from near Seattle, USA",
"license": "CC BY-SA 2.0",
"source": "https://commons.wikimedia.org/wiki/File:Lydian_electrum_Lion_coins_-_Flickr_-_brewbooks.jpg"
},
"tomato": {
"artist": "Softeis",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Tomato_je.jpg"
},
"democracy": {
"artist": "Philipp Foltz",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Discurso_funebre_pericles.PNG"
},
"buddha": {
"artist": "พระมหาเทวประภาส วชิรญาณเมธี (ผู้ถ่าย-ปล่อยสัญญาอนุญาตภาพให้นำไปใช้ได้เพื่อการศึกษาโดยอยู่ภา่ยใต้ cc-by-sa-3.0)  ผู้สร้าง",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Buddha_in_Sarnath_Museum_(Dhammajak_Mutra).jpg"
},
"confucius": {
"artist": "Anonymous Chinese painter of the Western Han period",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Confucius,_fresco_from_a_Western_Han_tomb_of_Dongping_County,_Shandong_province,_China.jpg"
},
"nok": {
"artist": "Ji-Elle",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Sculpture_nok-Nigeria_(1).jpg"
},
"alexander": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Alexander_Mosaic_detail_of_Alexander_the_Great_(3x4_cropped).jpg"
},
"library": {
"artist": "O. Von Corven",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Ancientlibraryalex.jpg"
},
"ashoka": {
"artist": "Photo Dharma from Sadao, Thailand",
"license": "CC BY 2.0",
"source": "https://commons.wikimedia.org/wiki/File:Ashoka%27s_visit_to_the_Ramagrama_stupa_Sanchi_Stupa_1_Southern_gateway.jpg"
},
"qin": {
"artist": "Unknown (18??–18??)",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:QinShiHuang19century.jpg"
},
"silkroad": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Zhang_Qian.jpg"
},
"monsoon": {
"artist": "Post of Zanzibar",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Stamp_of_Zanzibar_-_1944_-_Colnect_413543_-_1_-_Dhow_-_Map.jpeg"
},
"jesus": {
"artist": "unknown artist, circa 100-150 A.D.\nphoto made under direction of Joseph Wilpert, published 1903 photos in the book made ",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:The_Good_Shepherd,_Catacomb_of_Petrus_and_Marcellinus,_3rd_century_AD,_from_the_from_the_book_Die_Malereien_der_Katakomben_Roms,_pla_cropped_sharpenedmore.jpg"
},
"rome": {
"artist": "Justin Benttinen",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Augustus_of_Prima_Porta.jpg"
},
"paper": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Cai-lun.jpg"
},
"teotihuacan": {
"artist": "Hdlrosa",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:ZA77_Teotihuac%C3%A1n_edo_de_mex_Herberto_de_la_rosa.jpg"
},
"maya": {
"artist": "Mundo Maya",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Tikal_3.jpg"
},
"camel": {
"artist": "Sergey Pesterev",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Caravan_in_the_desert.jpg"
},
"christianrome": {
"artist": "Unknown Roman artist",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Missorium_of_Theodosius_I_(detail).png"
},
"romefalls": {
"artist": "Bernhard Mörlins (B. Moerlins)",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Romulus_Augustulus_and_Odoacer.jpg"
},
"justinian": {
"artist": "Josse Lieferinxe",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Plaguet03.jpg"
},
"buddhajapan": {
"artist": "Saigen Jiro",
"license": "CC0",
"source": "https://commons.wikimedia.org/wiki/File:Asuka-dera,_sanmon.jpg"
},
"islam": {
"artist": "Richard Mortel",
"license": "CC BY 2.0",
"source": "https://commons.wikimedia.org/wiki/File:The_Ka%27ba,_Great_Mosque_of_Mecca,_Saudi_Arabia_(4).jpg"
},
"zero": {
"artist": "National Geographic",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Bakhshali_manuscript_zero_detail.jpg"
},
"tea": {
"artist": "Gisling",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Chajing.jpeg"
},
"papersamarkand": {
"artist": "Stomac",
"license": "CC BY-SA 2.0 fr",
"source": "https://commons.wikimedia.org/wiki/File:Registan_Samarkand_Uzbekistan.JPG"
},
"baghdad": {
"artist": "Zereshk",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Maqamat_hariri.jpg"
},
"algebra": {
"artist": "Zarateman",
"license": "CC0",
"source": "https://commons.wikimedia.org/wiki/File:Madrid_-_Ciudad_Universitaria,_Monumento_a_Muhammad_al-Juarismi_(cropped).jpg"
},
"gunpowder": {
"artist": "Lord Mountbatten",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Black_Powder-1.JPG"
},
"ghanagold": {
"artist": "Luxo",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Ghana_empire_map.png"
},
"swahili": {
"artist": "Khalidsalewa",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Great_Mosque_Kilwa_Interior.jpg"
},
"hawaii": {
"artist": "HongKongHuey",
"license": "CC BY 2.0",
"source": "https://commons.wikimedia.org/wiki/File:Hokule%27aSailing2009.jpg"
},
"vikings": {
"artist": "Dylan Kereluk from White Rock, Canada",
"license": "CC BY 2.0",
"source": "https://commons.wikimedia.org/wiki/File:Authentic_Viking_recreation.jpg"
},
"movabletype": {
"artist": "BabelStone",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Ningxia_Museum_wooden_moveable_print_frame.jpg"
},
"cahokia": {
"artist": "Skubasteve834",
"license": "CC BY 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Monks_Mound_-_Summer_2024.jpg"
},
"crusades": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Peter_the_Hermit.jpg"
},
"compass": {
"artist": "",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Model_Si_Nan_of_Han_Dynasty.jpg"
},
"angkor": {
"artist": "Bjørn Christian Tørrissen",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Angkor_Wat.jpg"
},
"zimbabwe": {
"artist": "Andrew Moore from Johannesburg, South Africa",
"license": "CC BY-SA 2.0",
"source": "https://commons.wikimedia.org/wiki/File:Conical_Tower_-_Great_Enclosure_III_(33736918448).jpg"
},
"polysouth": {
"artist": "Hobe / Holger Behr",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Map_OC-Polynesia.PNG"
},
"fibonacci": {
"artist": "",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Liber_abbaci_magliab_f124r.jpg"
},
"genghis": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:YuanEmperorAlbumGenghisPortrait.jpg"
},
"magnacarta": {
"artist": "Original authors were the barons and King John of England. Uploaded by Earthsound.",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Magna_Carta_(British_Library_Cotton_MS_Augustus_II.106).jpg"
},
"rockets": {
"artist": "Jiao Yu and Liu Bowen",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Manual_Fire_Arrow.jpg"
},
"marcopolo": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Frontispice_%C3%A9dition_de_Nuremberg_1477_(cropped).png"
},
"papermill": {
"artist": "Raganella59",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Museo_della_carta_e_della_filigrana-3.jpg"
},
"aztec": {
"artist": "thomas kole",
"license": "CC BY 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Vista_completa_de_Tenochtitl%C3%A1n.jpg"
},
"mansamusa": {
"artist": "attributed to Abraham Cresques",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Catalan_Atlas_BNF_Sheet_6_Mansa_Musa_(cropped).jpg"
},
"blackdeath": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Burying_Plague_Victims_of_Tournai.jpg"
},
"catalan": {
"artist": "Cresques Abraham",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Compass_rose_from_Catalan_Atlas_(1375).jpg"
},
"renaissance": {
"artist": "",
"license": "CC BY 2.5",
"source": "https://commons.wikimedia.org/wiki/File:Lightmatter_Sistine_Chapel_ceiling_(cropped_and_rotated).jpg"
},
"zhenghe": {
"artist": "Marcin Konsek",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:2016_Malakka,_Stadhuys_(09).jpg"
},
"portugal": {
"artist": "Nuno Gonçalves",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Henry_the_Navigator1.jpg"
},
"malacca": {
"artist": "ToofanwikiCommon",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Inside_A_Famosa_gate_in_the_historical_city_of_Melaka_(or_Malacca),_Malaysia.jpg"
},
"inca": {
"artist": "Draceane",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Machu_Picchu,_2023_(012).jpg"
},
"hangul": {
"artist": "metalslick",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Hangul_chosongul_fontembed.svg"
},
"coffee": {
"artist": "John Frederick Lewis",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:John_Frederick_Lewis_004.jpg"
},
"gutenberg": {
"artist": "International Printing Museum",
"license": "CC0",
"source": "https://commons.wikimedia.org/wiki/File:Gutenberg_press.png"
},
"constantinople": {
"artist": "DimiTalen",
"license": "CC0",
"source": "https://commons.wikimedia.org/wiki/File:Siege_of_Constantinople_fresco,_Moldovi%C8%9Ba_monastery,_Vatra_Moldovi%C8%9Bei,_2017.jpg"
},
"columbus": {
"artist": "John Vanderlyn",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Landing_of_Columbus_(2).jpg"
},
"dagama": {
"artist": "Sailko",
"license": "CC BY 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Ignoto_portoghese,_ritratto_di_un_cavaliere_dell%27ordine_di_cristo,_1525-50_ca._02.jpg"
},
"exchange": {
"artist": "",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:VegCorn_(cropped).jpg"
},
"luther": {
"artist": "Lucas Cranach the Elder",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Martin_Luther_by_Cranach-restoration.tif"
},
"smallpox": {
"artist": "Bernardino de Sahagún.",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Healer_(ticitl)_tending_to_people_suffering_from_smallpox_in_1520_in_Book_12_of_the_Florentine_Codex,_1577.jpg"
},
"aztecfall": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Conquista-de-M%C3%A9xico-por-Cort%C3%A9s-Tenochtitlan-Painting.png"
},
"magellan": {
"artist": "Abraham Ortelius",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Detail_from_a_map_of_Ortelius_-_Magellan%27s_ship_Victoria.png"
},
"slavetrade": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Slave_Auction_Ad.jpg"
},
"incafall": {
"artist": "Juan Lepiani",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:La_Captura_de_Atahualpa_-_Juan_Lepiani_1920s.png"
},
"potosi": {
"artist": "Mhwater at Dutch Wikipedia",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Cerro_ricco.jpg"
},
"chili": {
"artist": "Takeaway",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Madame_Jeanette_and_other_chillies.jpg"
},
"tomatoitaly": {
"artist": "Anna.Massini",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Pomodori_San_Marzano_in_maturazione_-_biologici.jpg"
},
"chocolate": {
"artist": "Didier Descouens",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Ca%27_Rezzonico_-_La_cioccolata_del_mattino_-_Pietro_Longhi.jpg"
},
"manila": {
"artist": "Cornelis Verbeeck",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Spanish_Galleon_Firing_its_Cannon.jpg"
},
"sugar": {
"artist": "Urban Walnut",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Rose_Hall_(Jamaica).jpg"
},
"galileo": {
"artist": "Justus Sustermans",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Galileo_Galilei_(1564-1642)_RMG_BHC2700.tiff"
},
"jikji": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Jikji_pages.jpg"
},
"japanclosed": {
"artist": "Kawahara Keiga",
"license": "CC0",
"source": "https://commons.wikimedia.org/wiki/File:Het_eiland_Deshima_in_de_baai_van_Nagasaki_met_de_schepen_%27Vasco_da_Gama%27_uit_Gent_en_%27Johanna_Elisabeth%27_uit_Antwerpen.,_Keiga_Kawahara,_ca_1825,_MAS.jpg"
},
"coffeehouse": {
"artist": "The original uploader was Afro bighair at English Wikipedia.",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Rulesandorders.jpg"
},
"newton": {
"artist": "The original uploader was Zhaladshar at English Wikisource.",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Newton%27s_Principia_title_page.png"
},
"potatoeurope": {
"artist": "Robert Müller",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Robert_Warthm%C3%BCller_-_Der_K%C3%B6nig_%C3%BCberall_(1886).jpg"
},
"plainshorses": {
"artist": "George Catlin",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:George_Catlin_-_Buffalo_Bulls_Back_Fat_-_Smithsonian.jpg"
},
"enlightenment": {
"artist": "Anicet Charles Gabriel Lemonnier",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Les_salons_au_XVIIIe_si%C3%A8cle_-_Histoire_Image.jpg"
},
"teabritain": {
"artist": "Vanderdecken",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Nice_Cup_of_Tea.jpg"
},
"sevenyears": {
"artist": "Blaue Max",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Seven_Years%27_War_Collage.jpg"
},
"mills": {
"artist": "Illustrator T. Allom, Engraver J. Tingle",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Powerloom_weaving_in_1835.jpg"
},
"steam": {
"artist": "Nicolás Pérez",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Maquina_vapor_Watt_ETSIIM.jpg"
},
"cook": {
"artist": "Nathaniel Dance-Holland",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Captainjamescookportrait.jpg"
},
"amrev": {
"artist": "original: w:Second Continental Congress; reproduction: William Stone",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:United_States_Declaration_of_Independence.jpg"
},
"bostontea": {
"artist": "Original uploader was Cornischong at lb.wikipedia",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Boston_Tea_Party_w.jpg"
},
"constitution": {
"artist": "Constitutional Convention",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Constitution_of_the_United_States_-_DPLA_-_9ca804144bd5965e992ae3528bc3c6a3_(page_1).jpg"
},
"firstfleet": {
"artist": "Original drawing by R. Cleveley, engraving by T. Medland.",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:A_view_of_Botany_Bay_A1475003h_(cropped).jpg"
},
"frenchrev": {
"artist": "Unidentified painter",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Anonymous_-_Prise_de_la_Bastille.jpg"
},
"haiti": {
"artist": "Aaron Martinet / Alphonse-Charles Masson",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Incendie_de_la_Plaine_du_Cap._Massacre_des_Blancs_par_les_esclaves_noirs_r%C3%A9volt%C3%A9s._France_militaire._Martinet_et_Masson.jpg"
},
"cottongin": {
"artist": "Tom Murphy VII",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Cotton_gin_EWM_2007.jpg"
},
"jenner": {
"artist": "John Raphael Smith",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Edward_Jenner.jpg"
},
"louisiana": {
"artist": "William Morris",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Louisiana_Purchase.png"
},
"napoleon": {
"artist": "Jacques-Louis David / Georges Rouget",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Jacques-Louis_David_-_The_Coronation_of_Napoleon_(1805-1807).jpg"
},
"bolivar": {
"artist": "Martin Tovar y Tovar",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Sim%C3%B3n_Bol%C3%ADvar_-_Mart%C3%ADn_Tovar_y_Tovar.jpg"
},
"tambora": {
"artist": "This image was taken by the NASA Expedition 20 crew.",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Mount_Tambora_Volcano,_Sumbawa_Island,_Indonesia.jpg"
},
"nosummer": {
"artist": "Giorgiogp2",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:1816_summer.png"
},
"frankenstein": {
"artist": "Mary Shelley",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Christie%27s_auction_scan_of_Frankenstein_1818.jpg"
},
"bicycle": {
"artist": "Gun Powder Ma",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Draisine_or_Laufmaschine,_around_1820._Archetype_of_the_Bicycle._Pic_01.jpg"
},
"railway": {
"artist": "Kabelleger",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Locomotion_No._1_New_Bridge.jpg"
},
"darwin": {
"artist": "John Gould (14.Sep.1804 - 3.Feb.1881)",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Darwin%27s_finches_by_Gould.jpg"
},
"opium": {
"artist": "Edward Duncan",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Destroying_Chinese_war_junks,_by_E._Duncan_(1843).jpg"
},
"lovelace": {
"artist": "Antoine Claudet",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Ada_Lovelace_daguerreotype_by_Antoine_Claudet_1843_-_cropped.png"
},
"famine": {
"artist": "James Mahony",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Skibbereen_by_James_Mahony,_1847.JPG"
},
"thoreau": {
"artist": "Benjamin D. Maxham active 1848 - 1858",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Benjamin_D._Maxham_-_Henry_David_Thoreau_-_Restored.jpg"
},
"irishus": {
"artist": "Henry Edward Doyle",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Emigrants_Leave_Ireland_by_Henry_Doyle_1868.jpg"
},
"perry": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Japanese_1854_print_Commodore_Perry.jpg"
},
"oil": {
"artist": "Niagara",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Drake_Well,_June_2012.jpg"
},
"origin": {
"artist": "John Murray, Publisher",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Origin_of_Species_title_page.jpg"
},
"civilwar": {
"artist": "Nathaniel Currier and James Merritt Ives",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Battle_of_Gettysburg,_by_Currier_and_Ives.png"
},
"meiji": {
"artist": "Takahashi Yuichi (1828-1894)",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Emperor_Meiji_by_Takahashi_Yuichi.jpg"
},
"suez": {
"artist": "NASA",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Iss016e019375.jpg"
},
"milkchoc": {
"artist": "Chocosuisse (unknown photographer)",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Daniel_Peter.jpg"
},
"edison": {
"artist": "KMJ, alpha masking by Edokter",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Gluehlampe_01_KMJ.png"
},
"timezones": {
"artist": "Rodw at English Wikipedia",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Exchangeclock.JPG"
},
"africascramble": {
"artist": "Adalbert von Roessler",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Kongokonferenz.jpg"
},
"car": {
"artist": "DaimlerChrysler AG",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Patent-Motorwagen_Nr.1_Benz_2.jpg"
},
"pizza": {
"artist": "Bex Walton from London, England",
"license": "CC BY 2.0",
"source": "https://commons.wikimedia.org/wiki/File:Neapolitan_pizza_at_Trappica_(48701940197).jpg"
},
"gandhisa": {
"artist": "Elliott &amp; Fry",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Mahatma-Gandhi,_studio,_1931.jpg"
},
"adwa": {
"artist": "The Graphic, from details supplied by survivors",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Adoua_1.jpg"
},
"yellowfever": {
"artist": "Unidentified photographer",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:WalterReed.jpeg"
},
"wright": {
"artist": "John T. Daniels",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:First_flight2.jpg"
},
"einstein": {
"artist": "Oren Jack Turner",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Albert_Einstein_Head_cleaned.jpg"
},
"modelt": {
"artist": "ModelTMitch",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:1925_Ford_Model_T_touring.jpg"
},
"panama": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Labourers_at_work_on_the_panama_canal_at_Culebra_Cut_1904.jpg"
},
"ww1": {
"artist": "Collection DocAnciens/docpix.fr",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Bataille_de_Verdun_1916.jpg"
},
"russianrev": {
"artist": "unknown; photo retake by George Shuklin",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:%D0%9C%D0%B8%D1%82%D0%B8%D0%BD%D0%B3_%D0%BD%D0%B0_%D0%9D%D0%B5%D0%B2%D1%81%D0%BA%D0%BE%D0%BC_%D0%BF%D1%80%D0%BE%D1%81%D0%BF%D0%B5%D0%BA%D1%82%D0%B5_(1917).jpg"
},
"flu": {
"artist": "Otis Historical Archives, National Museum of Health and Medicine",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Emergency_hospital_during_Influenza_epidemic,_Camp_Funston,_Kansas_-_NCP_1603.jpg"
},
"versailles": {
"artist": "David Lloyd George, Woodrow Wilson and Georges Clemenceau",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Treaty_of_Versailles,_English_version.jpg"
},
"goddard": {
"artist": "NASA",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Dr._Robert_H._Goddard_-_GPN-2002-000131.jpg"
},
"penicillin": {
"artist": "Denise León",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Alexander_Fleming_Laboratory_Museum.jpg"
},
"depression": {
"artist": "Unknown authorUnknown author or not provided",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Unemployed_men_queued_outside_a_depression_soup_kitchen_opened_in_Chicago_by_Al_Capone,_02-1931_-_NARA_-_541927.jpg"
},
"saltmarch": {
"artist": "Yann (talk)",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Marche_sel.jpg"
},
"nazis": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Reichstagsbrand.jpg"
},
"ww2": {
"artist": "Richard Opitz",
"license": "CC BY-SA 3.0 de",
"source": "https://commons.wikimedia.org/wiki/File:Bundesarchiv_Bild_101I-646-5188-17,_Flugzeuge_Junkers_Ju_87.jpg"
},
"holocaust": {
"artist": "Bernhard Walter",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Selection_on_the_ramp_at_Auschwitz-Birkenau,_1944_(Auschwitz_Album)_1b.jpg"
},
"pearlharbor": {
"artist": "Imperial Japanese Navy",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Attack_on_Pearl_Harbor_Japanese_planes_view.jpg"
},
"turing": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Wartime_picture_of_a_Bletchley_Park_Bombe.jpg"
},
"v2": {
"artist": "AElfwine",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Fus%C3%A9e_V2_(cropped).jpg"
},
"hiroshima": {
"artist": "George R. Caron / Charles Levy",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Atomic_bombing_of_Japan.jpg"
},
"un": {
"artist": "Credit: Nicholas Morant / National Film Board of Canada. Phototheque / Library and Archives Canada / C-047570Photographe",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Canadian_Delegation_at_United_Nations_Conference_on_International_Organization_1945.jpg"
},
"india": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Jawaharlal_Nehru_delivering_his_%22tryst_with_destiny%22_speech.jpg"
},
"transistor": {
"artist": "Ulfbastel",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Transbauformen.jpg"
},
"udhr": {
"artist": "FDR Presidential Library &amp; Museum",
"license": "CC BY 2.0",
"source": "https://commons.wikimedia.org/wiki/File:Eleanor_Roosevelt_UDHR.jpg"
},
"who": {
"artist": "Guilhem Vellut from Annecy, France",
"license": "CC BY 2.0",
"source": "https://commons.wikimedia.org/wiki/File:World_Health_Organization_@_Pregny-Chamb%C3%A9sy_(50636746028).jpg"
},
"prc": {
"artist": "Orihara1",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Mao_Proclaiming_New_China.JPG"
},
"dna": {
"artist": "Rori!",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Rosalind_Franklin_CC-BY-SA.png"
},
"montgomery": {
"artist": "Unknown authorUnknown author",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Rosa_Parks,_November_1956_(cropped).jpg"
},
"ghana": {
"artist": "Brans Wyte GH",
"license": "CC0",
"source": "https://commons.wikimedia.org/wiki/File:The_Bronze_Head_of_Kwame_Nkrumah.jpg"
},
"sputnik": {
"artist": "Andrey Butko",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:%D0%9F%D0%B5%D1%80%D0%B2%D1%8B%D0%B9_%D0%B2_%D0%BC%D0%B8%D1%80%D0%B5_%D0%B8%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%82%D0%BD%D0%B8%D0%BA_%D0%97%D0%B5%D0%BC%D0%BB%D0%B8.jpg"
},
"keeling": {
"artist": "Oeneis",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Mauna_Loa_CO2_monthly_mean_concentration.svg"
},
"arpa": {
"artist": "DARPA-PAO",
"license": "CC BY 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Darpa-logo-2026.png"
},
"microchip": {
"artist": "cole8888, https://flickr.com/photos/187597251@N05/ (aka Cole L)",
"license": "CC BY-SA 2.0",
"source": "https://commons.wikimedia.org/wiki/File:NXP_PCF8577C_LCD_driver_with_I%C2%B2C_(Colour_Corrected).jpg"
},
"greenrev": {
"artist": "Sanyam Bahga",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:Punjab_Monsoon.jpg"
},
"earthrise": {
"artist": "NASA/Bill Anders",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:NASA-Apollo8-Dec24-Earthrise.jpg"
},
"apollo": {
"artist": "Neil A. Armstrong",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:A_Man_on_the_Moon,_AS11-40-5903_(cropped).jpg"
},
"arpanet": {
"artist": "ARPANET",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Arpanet_logical_map,_march_1977.png"
},
"earthday": {
"artist": "John McConnell (flag designer)NASA (Earth photograph)SiBr4 (flag image)",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Earth_Day_Flag.png"
},
"pc": {
"artist": "Rama &amp; Musée Bolo",
"license": "CC BY-SA 2.0 fr",
"source": "https://commons.wikimedia.org/wiki/File:Apple_II-IMG_7064.jpg"
},
"smallpoxgone": {
"artist": "James Gathany",
"license": "Public domain",
"source": "https://commons.wikimedia.org/wiki/File:Smallpox_vaccination_needle.jpg"
},
"www": {
"artist": "Geni",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:NeXTcube_first_webserver.JPG"
},
"berlinwall": {
"artist": "Unknown photographer, Reproduction by Lear 21 at English Wikipedia.",
"license": "CC BY-SA 3.0",
"source": "https://commons.wikimedia.org/wiki/File:West_and_East_Germans_at_the_Brandenburg_Gate_in_1989.jpg"
},
"mandela": {
"artist": "Kingkongphoto &amp; www.celebrity-photos.com from Laurel",
"license": "CC BY-SA 2.0",
"source": "https://commons.wikimedia.org/wiki/File:Nelson_Mandela_1994.jpg"
},
"smartphone": {
"artist": "Rafael Fernandez",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:IPhone_1st_Gen.svg"
},
"arabspring": {
"artist": "Skotch 79",
"license": "CC0",
"source": "https://commons.wikimedia.org/wiki/File:Zabadehors.JPG"
},
"paris": {
"artist": "UNclimatechange",
"license": "CC BY 2.0",
"source": "https://commons.wikimedia.org/wiki/File:Family_photo_during_the_Leader_Event_of_COP21_CMP_11_-_Paris_Climate_Change_Conference_(23360960261).jpg"
},
"covid": {
"artist": "Gustavo Basso",
"license": "CC BY-SA 4.0",
"source": "https://commons.wikimedia.org/wiki/File:Covid-19_SP_-_UTI_V._Nova_Cachoeirinha.jpg"
},
"mrna": {
"artist": "Whispyhistory",
"license": "CC0",
"source": "https://commons.wikimedia.org/wiki/File:COVID-19_vaccine_vial_(2024).jpg"
}
};
