"""Turn tools/images.json into images.js (credits for pictures that downloaded)."""
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
data = json.load(open(f"{ROOT}/tools/images.json"))
ok = {k: {"artist": v.get("artist", ""), "license": v["license"], "source": v["source"]}
      for k, v in data.items() if "error" not in v and os.path.exists(f"{ROOT}/img/{k}.jpg")}
open(f"{ROOT}/images.js", "w").write("// Generated by tools/build_images_js.py. Pictures from Wikimedia Commons, free licenses only.\nwindow.IMAGES = " + json.dumps(ok, ensure_ascii=False, indent=0) + ";\n")
print(len(ok), "pictures;", ", ".join(k for k, v in data.items() if "error" in v) or "no", "missing")
